.travis.yml
DependencyInjection/Configuration.php
DependencyInjection/OverblogGraphQLExtension.php
Request/BatchParser.php
Request/Executor.php
Request/Parser.php
Request/ParserInterface.php
Request/Validator/Rule/MaxQueryDepth.php
Resources/config/services.yml
Tests/Functional/Controller/GraphControllerTest.php
Tests/Request/Validator/Rule/MaxQueryDepthTest.php
Tests/Request/Validator/Rule/Schema.php

Add query max depth security

---

README.md
Resolver/Config/AbstractConfigSolution.php
Resolver/Config/FieldsConfigSolution.php

Resolver result is retrieve only if access return true for mutation operation type. This mean that `object` expression language can't no more be use on access field for mutation operation.

Fix mutation access control

---

Controller/GraphController.php
Controller/GraphiQLController.php
DependencyInjection/Configuration.php
DependencyInjection/OverblogGraphQLExtension.php
README.md
Request/Executor.php
Resources/config/routing/graphiql.yml
Resources/config/routing/graphql.yml
Resources/config/services.yml
Tests/Functional/Controller/GraphControllerTest.php
Tests/Functional/Controller/GraphiQLControllerTest.php
Tests/Request/ExecutorTest.php

Multiple schema endpoint
----------------------------------
```yaml
#app/config/config.yml
overblog_graphql:
definitions:
schema:
foo:
query: fooQuery
bar:
query: barQuery
mutation: barMutation
```
**foo** schema endpoint can be access:
type | Path
-----| -----
simple request | `/graphql/foo`
batch request | `/graphql/foo/batch`
graphiQL | `/graphiql/foo`
**bar** schema endpoint can be access:
type | Path
-----| -----
simple request | `/graphql/bar`
batch request | `/graphql/bar/batch`
graphiQL | `/graphiql/bar`

Enable multiple schema

---

README.md

Fix namespace for StarWarsData in README example

fix(README): StarWarsData namespace doc was wrong

---

DependencyInjection/Compiler/TaggedServiceMappingPass.php
Tests/DependencyInjection/Compiler/FakeCompilerPass.php
Tests/DependencyInjection/Compiler/FakeInjectedService.php
Tests/DependencyInjection/Compiler/ResolverTaggedServiceMappingPassTest.php
Tests/DependencyInjection/Compiler/ResolverTestService.php

Issue `$container->get()` should not be called during compiler passes to avoid issues where a resolver service (for instance), implements ContainerAwareInterface and for which a service is not fully yet created.
This fix uses `$container->findDefinition()` instead and checks if the class (string) is a sub class of the interface.

Avoid creating services before compiler passes are all done

---

Request/Executor.php

This changes the rounding of the execution time provided when debug mode is enabled. Now the precision should be of 1ms instead of 100ms.

Fixed round for execution time

---

Relay/Connection/Paginator.php
Tests/Relay/Connection/PaginatorTest.php

This adds a standalone object to help on pagination. Its role is to convert GraphQL arguments from the ConnectionArgs to an offset/limit pair. For instance : 
```php
public function resolveList($args)
{
$pagination = new EntityPaginator(function ($offset, $limit) {
return $this->myRepository->getAll($offset, $limit); // Or Doctrine or whatever
});
// Make use of the 'first' and 'after' arguments
return $pagination->forward($args);
}
```
All you have to do is provide a callable that fetch the items you need to paginate.
For backward pagination, you have to provide an item count : 
```php
return $pagination->backward($args, $this->myRepository->count());
```
You can also have an automatic mode that detects if you go backward or forward : 
```php
return $pagination->auto($args, …
```

Added paginator helper to convert first/after and before/last to offset/limit

---

Relay/Connection/Paginator.php
Resources/doc/helpers/relay-paginator.md
Tests/Relay/Connection/PaginatorBackend.php
Tests/Relay/Connection/PaginatorTest.php

Make it possible to pass arguments for the callable used in the `auto` and `backward` function of the `Paginator`.

Paginator backward method now accepts arguments for its callback

---

Config/EnumTypeDefinition.php
Resources/doc/definitions/system-types/enum.md
Resources/doc/definitions/system-types/object.md
Tests/Functional/TestCase.php
Tests/Functional/Type/DefinitionTest.php
Tests/Functional/app/config/definition/config.yml
Tests/Functional/app/config/definition/mapping/deprecated.types.yml

Add deprecation reason tests

---

Resources/doc/definitions/index.md
Resources/doc/definitions/mutation.md
Resources/doc/definitions/relay/mutation.md

Add documentation for mutation without relay

---

Controller/GraphiQLController.php
DependencyInjection/Configuration.php
DependencyInjection/OverblogGraphQLExtension.php
Resources/views/GraphiQL/index.html.twig

| Documented?   | N/A
When using GraphiQL with browsers that do not natively support `window.fetch` (such as Safari in my case, but also older versions of Chrome, Firefox and IE), javascript errors pop up and GraphiQL becomes unusable.
The example HTML that GraphiQL themselves provide uses the whatwg-fetch polyfill as a workaround.
See https://github.com/graphql/graphiql/blob/master/example/index.html#L31 and https://www.npmjs.com/package/whatwg-fetch for more information.

Use the whatwg-fetch polyfill for GraphiQL

---

Error/ErrorHandler.php

This PRs adds compatibility for php7 by also handling the `\Error` class.

Added php7 errors compatibility

---

Relay/Connection/Paginator.php
Resources/doc/helpers/relay-paginator.md
Tests/Relay/Connection/PaginatorTest.php

This adds promise support on the paginator helper for connections.

Added promise handling on Paginator

---

Resources/views/GraphiQL/index.html.twig

| Fixed tickets | no
This PR is a small improvement which will update the Symfony toolbar when using GraphiQL in dev mode.

Update the whole Sf toolbar when using GraphiQL

---

Executor/Promise/Adapter/ReactPromiseAdapter.php
ExpressionLanguage/AuthorizationExpressionProvider.php
Tests/Executor/Promise/Adapter/ReactPromiseAdapterTest.php
composer.json

| Documented? |   no
Fix memory leak in react adapter wait
Also remove dead code and add react promise composer suggest.

Optimize react promise

---

Resources/views/GraphiQL/index.html.twig
Tests/Functional/app/config/routing.yml

Takes account of the generated url to avoid 404 when using `app_dev.php` base path.

Fix sf toolbar updates when using graphiql

---

Tests/Functional/app/Resolver/ConnectionResolver.php

| Fixed tickets | nono
Replaced `Overblog\GraphQLBundle\Executor\Promise\Adapter\GraphQLPromiseAdapter` by native `GraphQL\Executor\Promise\Adapter\SyncPromiseAdapter`.

Fix connection test resolver

---

ExpressionLanguage/ConfigExpressionProvider.php
Relay/Connection/Output/ConnectionBuilder.php
Relay/Mutation/MutationFieldDefinition.php
Relay/Mutation/MutationFieldResolver.php
Relay/Node/NodeFieldDefinition.php
Relay/Node/NodeFieldResolver.php
Relay/Node/PluralIdentifyingRootFieldDefinition.php
Resources/config/graphql_resolvers.yml
Tests/Functional/Relay/Mutation/MutationTest.php
Tests/Functional/app/Mutation/SimplePromiseMutation.php
Tests/Functional/app/config/mutation/mapping/Inputs.types.yml
Tests/Functional/app/config/mutation/mapping/Payloads.types.yml
Tests/Functional/app/config/mutation/mapping/RootMutation.types.yml
Tests/Functional/app/config/mutation/services.yml
Tests/Relay/Connection/Output/AbstractConnectionBuilderTest.php
Tests/Relay/Connection/Output/ConnectionBuilderFromPromisedTest.php
Tests/Relay/Connection/Output/ConnectionBuilderTest.php
Tests/Relay/Node/NodeFieldDefinitionTest.php
Tests/Relay/Node/PluralIdentifyingRootFieldDefinitionTest.php

Relay promise compatibility

---

Command/GraphQLDumpSchemaCommand.php
Tests/Functional/Command/GraphDumpSchemaCommandTest.php
Tests/Functional/Command/schema.graphqls
composer.json

Schema can also be dump in `graphqls` format...

Add format option to `graphql:dump-schema` command

---

Resources/views/GraphiQL/index.html.twig

| Fixed tickets | -
When running in `prod` the `_wdt` route is not available.
Leads to this PHP error:
```
Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "_wdt" as such route does not exist.").
```
Regression introduced in [this commit](https://github.com/overblog/GraphQLBundle/commit/e5ae4ed0cc13df67af7f04544dcbe88d64e4805b). 
PS: I love this bundle!

Regression: Fix graphiql route when running in the prod env

---

Command/GraphQLDumpSchemaCommand.php
Tests/Functional/Command/schema.json

Prettify json schema dump

---

Tests/Functional/Generator/TypeGeneratorTest.php
Tests/Functional/Security/AccessTest.php
Tests/Functional/Security/QueryComplexityTest.php
Tests/Functional/TestCase.php
Tests/Functional/app/config/access/config.yml
Tests/Functional/app/config/public/config.yml
Tests/Functional/app/config/security.yml

Refactor access public and complexity query tests

---

DependencyInjection/Compiler/ResolverTaggedServiceMappingPass.php
Resolver/AbstractProxyResolver.php
Tests/Functional/app/Exception/ExampleException.php
Tests/Functional/app/config/exception/services.yml

Allow omitting resolver and mutation method in tag config #133
| Fixed tickets | #133

Adjusted tagged proxy resolver method param to be optional

---

Resources/doc/definitions/graphiql/custom-http-headers.md
Resources/doc/definitions/graphiql/index.md
Resources/doc/definitions/index.md

| Fixed tickets | #131 partially 
Documentation as proposed in #131.

Add graphiql custom http headers documentation

---

DependencyInjection/Compiler/AutowiringTypesPass.php
DependencyInjection/OverblogGraphQLExtension.php
OverblogGraphQLBundle.php

Fix promise adapter autowire types

---

Resolver/TypeResolver.php

this was leading to duplication of types when unserialized cache

Disabled type resolver cache serialization

---

Config/ObjectTypeDefinition.php
Generator/TypeGenerator.php
Resources/doc/security/fields-public-control.md
Resources/skeleton/TypeSystem.php.skeleton

Added fieldsDefaultPublic that work like fieldsDefaultAccess

---

Controller/GraphController.php
DependencyInjection/Configuration.php
DependencyInjection/OverblogGraphQLExtension.php
Resources/doc/security/handle-cors-preflight-option.md
Resources/doc/security/index.md
Tests/Functional/App/config/connectionWithCORSPreflightOptions/config.yml
Tests/Functional/Controller/GraphControllerTest.php
composer.json

Add a generic and simple CORS preflight options handler

---

Command/GraphQLDumpSchemaCommand.php
DependencyInjection/Configuration.php
DependencyInjection/OverblogGraphQLExtension.php
Tests/Functional/Command/GraphDumpSchemaCommandTest.php
Tests/Functional/Command/fixtures/schema.modern.json

| Fixed tickets | #150 
If not using `modern` or `classic` flag the command will default on `classic` behavior. If you want to change this, you can use bundle config:
```yaml
overblog_graphql:
versions:
relay: modern
```

Add json schema dump modern relay compiler flag

---

Error/ErrorHandler.php
Tests/Error/ErrorHandlerTest.php

* Add GraphQL native UserError to white list
* Removed `InvariantViolation` from white list because this could lead to security issues ([see here](https://github.com/webonyx/graphql-php/issues/123))

Add GraphQL native UserError to white list

---

.travis.yml

Fix this error HHVM is no longer supported on Ubuntu Precise. Please consider using Trusty with `dist: trusty`.

Fix hhvm travis build

---

Resources/doc/definitions/type-system/interface.md

In ``services.yml`` the type resolver is an argument, but ``CharacterResolver`` doesn't have a ``__construct`` to handle that argument. It does work, because ``CharacterResolver`` is container aware. Replacing container aware by a construct makes the class look nice and the example more clear.

[Documentation] ``services.yml`` didn't match ``CharacterResolver``

---

Controller/GraphController.php
DependencyInjection/Configuration.php
DependencyInjection/OverblogGraphQLExtension.php
Resources/doc/data-fetching/batching.md
Resources/doc/data-fetching/index.md
Resources/doc/index.md

| Fixed tickets | #163 
Makes the batching method configurable. Apollo just wants the plain payload without any id attached to it. Not sure how to properly test the code since it requires switching a config value at run-time which is not possible as I just found out..
```php
/**
* @param $uri
* @dataProvider graphQLBatchEndpointUriProvider
*/
public function testBatchEndpointApolloStyleAction($uri)
{
$client = static::createClient(['test_case' => 'connection']);
$data = [
[
'query' => $this->friendsQuery
],
[
'query' => $this->friendsTotalCountQuery
]
];
$client->request('POST', $uri, [], [], …
```

Allow different methods of batching

---

Generator/TypeGenerator.php

| Fixed tickets | #167 
Replaced hard-coding absolute path by `__DIR__` (see #167)

Make classmap more flexible

---

DependencyInjection/Configuration.php
Tests/Functional/Security/QueryMaxDepthTest.php
Tests/Functional/app/config/queryComplexityEnv/config.yml
Tests/Functional/app/config/queryMaxDepth/config.yml
Tests/Functional/app/config/queryMaxDepth/mapping/connectionSimple.types.yml
Tests/Functional/app/config/queryMaxDepthEnv/config.yml

| Fixed tickets | #172 
This PR allows to use environment variables for query max depth and query complexity parameters

#172 Support environment variables for max depth and query complexity

---

Definition/Builder/SchemaBuilder.php
DependencyInjection/OverblogGraphQLExtension.php
Error/ErrorHandler.php
Executor/Executor.php
Executor/ExecutorInterface.php
Request/Executor.php
Tests/Functional/App/config/global/mapping/global.types.yml
Tests/Functional/Command/fixtures/schema.json
Tests/Functional/Command/fixtures/schema.modern.json
Tests/Functional/Type/DefinitionTest.php
Tests/Request/ExecutorTest.php
composer.json

Add support for `webonyx/graphql-php#v0.10`

---

Relay/Connection/Output/Connection.php
Relay/Connection/Paginator.php
Tests/Relay/Connection/PaginatorTest.php

WIP, waiting for your feedback and tests to be fixed
This PR adds a way to store the total count (if possible, so only via the `auto` method of the Paginator object).
| Documented?   | no yet, waiting feedback first

Store totalCount in paginator

---

Definition/Builder/SchemaBuilder.php
DependencyInjection/Compiler/TaggedServiceMappingPass.php
Resolver/AbstractResolver.php
Resolver/ResolverInterface.php
Resolver/TypeResolver.php
Tests/Functional/App/config/global/config.yml
Tests/Resolver/AbstractProxyResolverTest.php
Tests/Resolver/AbstractResolverTest.php
Tests/Resolver/TypeResolverTest.php

| Fixed tickets | #184 
This change introduce lazy loading for `TypeResolver` but also for resolver and mutation... Unfortunately when enabling the schema validation with `assertValid` method the `config.types` is required because `config.typeLoader` does not provide any full loader method.
**edit**: [here is the solution](https://github.com/webonyx/graphql-php/issues/168)

Add support for schema typeLoader

---

Tests/Definition/ArgumentTest.php
Tests/DependencyInjection/Compiler/ResolverTaggedServiceMappingPassTest.php
Tests/DependencyInjection/OverblogGraphQLTypesExtensionTest.php
Tests/Error/ErrorHandlerTest.php
Tests/Executor/Promise/Adapter/ReactPromiseAdapterTest.php
Tests/ExpressionLanguage/AuthorizationExpressionProviderTest.php
Tests/ExpressionLanguage/ConfigExpressionProviderTest.php
Tests/Functional/Controller/GraphControllerTest.php
Tests/Relay/Connection/Output/AbstractConnectionBuilderTest.php
Tests/Relay/Connection/PaginatorTest.php
Tests/Relay/Mutation/MutationFieldDefinitionTest.php
Tests/Relay/Node/GlobalIdTest.php
Tests/Relay/Node/NodeFieldDefinitionTest.php
Tests/Relay/Node/PluralIdentifyingRootFieldDefinitionTest.php
Tests/Request/ExecutorTest.php
Tests/Resolver/AbstractResolverTest.php
Tests/Resolver/ResolverTest.php
composer.json

The current nightly building is failing because on PHP 7.2+ the function each is deprecated, this one is being used on phpunit 4 and 5.
By upgrading phpunit to 6 the build will normally run on php 7.2+
The change which is regards to the TestCase class still works on phpunit 4, thus making sure no BC break is introduced

Compatible with PHP 7.2+ and PHPUnit 6+

---

Resolver/AbstractResolver.php
Resolver/TypeResolver.php

When using lazy loading with big schema and xdebug
we got "PHP Fatal error:  Maximum function nesting level of '1000' reached, aborting!"...

Fix max nesting error with big schema

---

.travis.yml

- Making travis file more readable within `script` test
- Using composer optimized autoloader for faster builds
Suggestions:
- Use `perfer-source` on composer, since we're saving composer cache by using the git repo it'll checkout the code faster, should I do it?
- Wouldn't be better to make the coverage under php 7+ due to performance?
- What about caching .php_cs.cache? It will always check for the updated files anyway

Improving Travis build

---

DependencyInjection/Configuration.php

| BC breaks?    | yes/no
- Updated to use the current way twig understands namespaces: https://symfony.com/doc/current/templating/namespaced_paths.html
- This will contribute for future SF 4.0 support
Quote from docs:
> In the past, Symfony used a different syntax to refer to templates. This format, which uses colons (:) to separate each template path section, is less consistent and has worse performance than the Twig syntax.

Using current Twig namespace on configuration

---

.travis.yml
composer.json

| Fixed tickets | #193
It's still a bit restrictive, but as I can see there is no branch for 0.12. I suggest to keep an eye on the library release cycle and try to align it.
Since their objective is to keep versioning in sync with the JS library wouldn't be hard to keep track of it

Supporting webonyx/graphql-php ^0.11.0

---

DependencyInjection/Compiler/AutowiringTypesPass.php

| Fixed tickets | #204 
this remove deprecation message (`Autowiring-types are deprecated since Symfony 3.3 and will be removed in 4.0. Use aliases instead.`)

Remove autowiring deprecation warning

---

Controller/GraphController.php
Resources/config/routing/graphql.yml
Resources/config/services.yml

- I just want to do some code enhancements and this is a step to symfony 4.0 as well
- I need some help on how to fix the tests, what's the best way to do it?
- Obs: I won't do it for GraphiQLController since my plan is to split it

GraphQLController as a Service

---

Command/DebugCommand.php
Command/GraphQLDumpSchemaCommand.php
Resources/config/services.yml
Tests/Functional/Command/DebugCommandTest.php
Tests/Functional/Command/GraphDumpSchemaCommandTest.php

| Deprecations? | fixes some deprecations
- Now all commands can be services
- When using the services in the tests avoids the commands auto registering, removing 14 deprecation warnings from the tests
- Using services allows the users to take over or change services by their desires using compiler passes

Refactor Commands to be services

---

Command/GraphQLDumpSchemaCommand.php
Resources/config/services.yml

| Documented?   | yno
| Fixed tickets | #211 
`overblog_graphql.request_executor` service must be load lazily since that command service
is instanced before `ClassLoaderEvent.` This issues is fix in Symfony 3.4 introducing lazy commands
see https://symfony.com/blog/new-in-symfony-3-4-lazy-commands...

Load `RequestExecutor` lazily to fix lazy command troubleshooting

---

Resources/doc/definitions/type-system/index.md

| Fixed tickets | #216 
Just adding documentation saying that type folders include sub-folders.

Add info that type folders include sub-folders

---

Resources/doc/definitions/schema.md

| Bug fix?      | /no
As @renatomefi suggested, I changed this so we have the different ways to use it

add different examples to the resolver example

---

.travis.yml
composer.json

- Trying to find out the lowest possible versions the bundle is compatible with
- Slight improves on travis build
----- OLD
- Sadly we don't support expression language 3.1
- Check it's constructor: https://github.com/symfony/symfony/blob/v3.1.10/src/Symfony/Component/ExpressionLanguage/ExpressionLanguage.php#L38
- Now on version 3.2: https://github.com/symfony/symfony/blob/v3.2.0/src/Symfony/Component/ExpressionLanguage/ExpressionLanguage.php#L40
And that's how we use it, as on 3.2: https://github.com/overblog/GraphQLBundle/blob/v0.9.2/ExpressionLanguage/ExpressionLanguage.php#L26

Finding and testing lowest possible versions

---

Config/Parser/XmlParser.php
Config/Parser/YamlParser.php
Tests/DependencyInjection/OverblogGraphQLTypesExtensionTest.php

Previously, if the contents of a type file were all commented out, it would return null which goes against the method signature and would break the call to `$container->prependExtensionConfig()`, in `OverblogGraphQLTypesExtension::prependExtensionConfigFromFiles()`.

cast to array the result of parsing yml and xml.

---

Resources/doc/security/errors-handling.md

Fixed missing `;` for use in that doc :-)

Missing semicolon in examples

---

CacheWarmer/CompileCacheWarmer.php
Command/CompileCommand.php
DependencyInjection/Compiler/ConfigTypesPass.php
DependencyInjection/Compiler/TaggedServiceMappingPass.php
DependencyInjection/Compiler/TypeTaggedServiceMappingPass.php
DependencyInjection/Configuration.php
DependencyInjection/OverblogGraphQLExtension.php
Generator/TypeGenerator.php
Resolver/TypeResolver.php
Resources/config/services.yml
Resources/doc/index.md
Resources/skeleton/TypeSystem.php.skeleton
Tests/Functional/App/config/generatorCommand/config.yml
Tests/Functional/Command/CompileCommandTest.php
Tests/Functional/Security/AccessTest.php
composer.json

Explicit types generation

---

DependencyInjection/Configuration.php
DependencyInjection/OverblogGraphQLExtension.php
Error/ErrorHandler.php
Resources/config/services.yml
Resources/doc/security/errors-handling.md
Tests/Error/ChildOfInvalidArgumentException.php
Tests/Error/ErrorHandlerTest.php

We would very much like to have the possibility of adding an exception to `overblog_graphql.definitions.exceptions.errors` and have its subclasses also be caught and handled by the ErrorHandler. (it would avoid us to explicitly add all exceptions to the config)
This PR adds an option to the config, to do exactly that.

add inheritance exception mapping option

---

Relay/Connection/Paginator.php

Currently with Relay pagination, if you don't include a `first` parameter in your query, your response will be limited to 1 result.
This is because the logic was, for instance: `$limit + 1`, so even if `$limit` was `null`, we'd still end up limiting to 1.

Bugfix: [Relay Pagination] Fixed query limit if no 'first' parameter set

---

UPGRADE-0.11.md

- Documenting the fact some graphiql versions were removed from the GraphQLBundle
How it looks like: https://github.com/renatomefi/overblog-GraphQLBundle/blob/documentation/upgrade-0.11-js-versions/UPGRADE-0.11.md

Upgrade 0.11: Versions removal

---

Resources/doc/definitions/type-inheritance.md

| Documented?   | x
Hi, 
I found a mistake in the doc. 
If I understand correctly this new feature (great work btw), `ObjectA` extends from `InterfaceA` and `ObjectC`.
Since `ObjectC` has one field `baz`, and `InterfaceA` has those fields :
- `bar`
- `bar2`
- `bar3`
That means that `ObjectA` should have those fields right? :
- `baz`
- `bar`
- `bar2`
- `bar3`

Documentation/Type inheritance: fix typo

---

DependencyInjection/Compiler/AliasedPass.php
DependencyInjection/Compiler/AutoMappingPass.php
DependencyInjection/Compiler/ConfigTypesPass.php
OverblogGraphQLBundle.php
Resources/doc/definitions/resolver.md

Move Aliased to dedicated compiler pass

---

.travis.yml
Config/CustomScalarTypeDefinition.php
Tests/Functional/App/config/customScalar/mapping/Query.types.yml
Tests/Functional/Type/CustomScalarTest.php
composer.json

When a new custom-scalar type defined we can't add description field to it. This patch add current functionality.

Add description field to custom-scalar type

---

Controller/GraphController.php

Hi there.
I think using interfaces in __construct parameters will be better. I want to override parser but cannot do that without this changes.
Test not passed with and without my changes.
```
RuntimeException: Type class for alias "RootQuery" could not be load. If you are using your own classLoader verify the path and the namespace please.
Class 'Overblog\GraphQLBundle\Access\__DEFINITIONS__\RootQueryType' not found
```
```
ERRORS!
Tests: 254, Assertions: 492, Errors: 10.
Remaining deprecation notices (1)
Autowire custom tagged (type, resolver or mutation) services is deprecated as …
```

use ParserInterface in GraphController constructor instead of parser classes

---

Resources/doc/definitions/type-inheritance.md

| Documented?   | x
The old key `extends` was still used in an example.
And since it was removed for the key `inherits`, I just updated the example :man_shrugging:

Update « extends » to « inherits » in type inheritance documentation

---

Resolver/AbstractResolver.php
Resolver/TypeResolver.php
Resources/doc/definitions/resolver.md
Resources/doc/definitions/type-system/index.md
Tests/Functional/App/GraphQL/HelloWord/Type/MutationType.php
Tests/Functional/App/GraphQL/HelloWord/Type/QueryType.php
UPGRADE-0.11.md

| Fixed tickets | #278
see [changes here](https://github.com/mcg-web/GraphQLBundle/blob/2e82d693f3bb27b1fb93e8d9fbe60635f5198566/UPGRADE-0.11.md#type-automapping-and-symfony-di-autoconfigure)

Remove type resolver postLoad

---

Resources/doc/definitions/builders/args.md

In [Args Builder documentation](https://github.com/overblog/GraphQLBundle/blob/master/Resources/doc/definitions/builders/args.md), some lines were missing (`type:`, `config:` and `fields:`).

[Doc] ArgsBuilder: add missing lines in example

---

Definition/Builder/SchemaBuilder.php
DependencyInjection/Configuration.php
DependencyInjection/OverblogGraphQLExtension.php
Resources/doc/definitions/relay/node/node.md
Resources/doc/definitions/schema.md
Tests/Functional/App/config/node/config.yml
UPGRADE-0.11.md

| Bug fix?      | yes/no
**Before 0.11** all types was declare as non detected types, this was not the correct way of declaring types.
This could lead to some performances issues or/and wrong types public exposition (in introspection query).
[See webonyx/graphql-php documentations for more details](http://webonyx.github.io/graphql-php/type-system/schema/#configuration-options)
**Since 0.11** Non detect types should be explicitly declare
here a concrete example:
```yaml
Query:
type: object
config:
fields:
foo: {type: FooInterface!}
FooInterface:
type: interface
config:
fields:
id: {type: ID!} …
```

Impose explicit declaration of non detected types

---

Config/CustomScalarTypeDefinition.php
Definition/Type/CustomScalarType.php
Definition/Type/SchemaDecorator.php
Generator/TypeGenerator.php
README.md
Request/BatchParser.php
Request/Parser.php
Request/UploadParserTrait.php
Resolver/ResolverMapInterface.php
Resources/doc/definitions/resolver-map.md
Resources/doc/definitions/type-system/scalars.md
Resources/doc/definitions/upload-files.md
Resources/skeleton/CustomScalarConfig.php.skeleton
Tests/Definition/Type/CustomScalarTypeTest.php
Tests/Definition/Type/SchemaDecoratorTest.php
Tests/Functional/App/Resolver/SchemaLanguageQueryResolverMap.php
Tests/Functional/App/Type/YearScalarType.php
Tests/Functional/App/config/upload/config.yml
Tests/Functional/App/config/upload/mapping/schema.types.yaml
Tests/Functional/Controller/GraphControllerTest.php
Tests/Functional/Upload/UploadTest.php
Tests/Functional/Upload/fixtures/a.txt
Tests/Functional/Upload/fixtures/b.txt
Tests/Functional/Upload/fixtures/c.txt
Tests/Request/UploadParserTraitTest.php
Tests/Upload/Type/GraphQLUploadTypeTest.php
Upload/Type/GraphQLUploadType.php

Make this bundle request parser complient with [jaydenseric/graphql-multipart-request-spec](https://github.com/jaydenseric/graphql-multipart-request-spec).
Unfortunately  [Ecodev/graphql-upload](https://github.com/Ecodev/graphql-upload) does not supports `php < 7.1`.

Add apollo upload server supports

---

Command/DebugCommand.php
Config/Processor/NamedConfigProcessor.php
Config/TypeDefinition.php
DependencyInjection/Compiler/ConfigTypesPass.php
DependencyInjection/Compiler/TaggedServiceMappingPass.php
Resolver/AbstractResolver.php
Resolver/FluentResolverInterface.php
Tests/Functional/Command/fixtures/case-sensitive/debug-resolver.txt
Tests/Functional/Command/fixtures/debug-resolver.txt
Tests/Resolver/AbstractProxyResolverTest.php
Tests/Resolver/AbstractResolverTest.php
Tests/Resolver/TypeResolverTest.php

Now fluent resolver use true aliases and stop duplicating resolver solution.

Improve fluent resolver aliases

---

.travis.yml
Definition/Builder/SchemaBuilder.php
Definition/Type/ExtensibleSchema.php
Definition/Type/SchemaExtension/DecoratorExtension.php
Definition/Type/SchemaExtension/SchemaExtensionInterface.php
Definition/Type/SchemaExtension/ValidatorExtension.php
DependencyInjection/OverblogGraphQLExtension.php
Event/ExecutorArgumentsEvent.php
Request/Executor.php
Resolver/ResolverMapInterface.php
Resources/config/services.yml
Tests/Definition/Type/SchemaExtension/DecoratorExtensionTest.php
Tests/Request/ExecutorTest.php

Introduce a way to easily extends schema with external extensions

Introduce extensible schema

---

Generator/TypeGenerator.php
Resources/skeleton/TypeSystem.php.skeleton

| Fixed tickets | #300 
This adds a NAME constant in generated type classes, like this:
```
/**
* THIS FILE WAS GENERATED AND SHOULD NOT BE MODIFIED!
*/
final class ViewerType extends InputObjectType implements GeneratedTypeInterface
{
const NAME = 'Viewer';
public function __construct(ConfigProcessor $configProcessor, GlobalVariables $globalVariables = null)
{
$configLoader = function(GlobalVariables $globalVariable) {
```
I'm not sure how to add tests for this, though.

Add a NAME constant in generated type classes

---

Command/GraphQLDumpSchemaCommand.php
Tests/Functional/Command/GraphDumpSchemaCommandTest.php
Tests/Functional/Command/fixtures/schema.descriptions.json

This adds a `with-descriptions` option to the `graphql:dump-schema` command.

Dump schema: Adds option to export schema with descriptions

---

Resources/doc/definitions/resolver.md

Just a minor typo fix because of YAML parse error for the double usage of simple quotes

Fix minor typo in documentation

---

Resources/doc/definitions/resolver.md
Resources/doc/definitions/type-system/enum.md
Resources/doc/helpers/relay-paginator.md

Improving some documentation pages based on what I have understood of the use of the bundle!
Lets me know if it's wrong or may be improved.

Improving doc

---

Resources/doc/definitions/expression-language.md

| Tests pass?   | n/a
| Fixed tickets | n/a
Updated a page in the docs.

Fixed typos and changed the wording slightly.

---

Resources/config/routing/graphql.yml
Resources/config/services.yml

| New feature?  | /no
A new deprectated is coming with SF 4.1 ;-) 
> With Passion !

User Deprecated: Referencing controllers with a single colon is deprecated since Symfony 4.1

---

Resources/doc/definitions/type-system/enum.md

Example a ENUM type with a PHP constant

Example with a PHP constant

---

.travis.yml
Command/GraphQLDumpSchemaCommand.php
Config/Parser/GraphQLParser.php
Definition/Type/CustomScalarType.php
DependencyInjection/Configuration.php
DependencyInjection/OverblogGraphQLExtension.php
Resources/config/services.yml
Tests/Config/Parser/GraphQLParserTest.php
Tests/Config/Parser/fixtures/graphql/schema-0.11.graphql
Tests/Functional/App/Type/YearScalarType.php
Tests/Functional/Command/GraphDumpSchemaCommandTest.php
Tests/Functional/Command/fixtures/schema.graphql
Tests/Functional/Upload/UploadTest.php
Upload/Type/GraphQLUploadType.php
composer.json

Allow webonyx/graphql-php 0.12

---

Config/Processor/InheritanceProcessor.php
Tests/Config/Processor/InheritanceProcessorTest.php

| Tests pass?   | no test
- Entity type is interface2
- SubscriptionDiscount inherits Entity
Exception message is:
_Type "Entity" can't inherits "SubscriptionDiscount" because "interface2" is not allowed type (["object","interface"])_
and should be:
_Type "SubscriptionDiscount" can't inherit "Entity" because its type ("interface2") is not allowed type (["object","interface"])_

Typo in exception

---

Resources/doc/definitions/type-inheritance.md

A concrete example for decorator usage and separate it from the other inheritance docs by own title. This feature should not be hidden as side note mentioning :) .

doc(type-inheritance): added an usage example for decorators

---

Resources/config/routing/graphql.yml
Resources/config/services.yml

Apply patch to remove Symfony 4.1 deprecation message

---

ExpressionLanguage/ExpressionFunction/GraphQL/IsTypeOf.php
ExpressionLanguage/ExpressionFunction/Security/IsAuthenticated.php

| Documented?   | not applicable
| Fixed tickets | no issue opened
I encountered an issue with some complex `access` expressions : 
```
"@=isAuthenticated() && (getUser().getId() == value.getId())"
```
Would mess with operator priorities by getting compiled to : 
```php
'access' => function ($value, $args, $context, ResolveInfo $info, $object) use ($globalVariable) {
return ($globalVariable->get('container')->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_REMEMBERED') || $globalVariable->get('container')->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_FULLY') && …
```

Wrapped complex expressions inside parenthesis to enforce operator priority

---

DependencyInjection/Configuration.php
DependencyInjection/OverblogGraphQLExtension.php
README.md
Request/Executor.php
Resources/doc/security/disable_introspection.md
Resources/doc/security/index.md
Tests/Functional/App/config/disableIntrospection/config.yml
Tests/Functional/Security/DisableIntrospectionTest.php

| Fixed tickets | -
This PR adds a configuration setting to disable introspection queries. See http://webonyx.github.io/graphql-php/security/#disabling-introspection
I have added a test case, but 12 tests did already fail on branch 0.11.

Add config option to disable introspection query

---

src/Resolver/AccessResolver.php
tests/Functional/App/config/access/mapping/access.types.yml
tests/Functional/Security/AccessTest.php

| Documented?   | bugfix?
| Fixed tickets | #387
Resolved array values has been treated as ListOfType in regards to access check. Full information see #387

Fix for #387

---

src/Controller/GraphController.php

OPTIONS http request is used by browsers to fetch CORS from server. I would like to change the content of body because I think an empty response is a bad behavior.
We use Cloudflare in front of our API and it considers that empty body response is an error.
I'm not sure about what we need to send instead of an empty response and I suggest an empty array.

Add content to body with OPTIONS verb

---

docs/security/fields-public-control.md

This field goes under `config`, not at the root.
Simple doc fix for the usage example of `fieldsDefaultPublic`, supposed to go below `config`.

Fixed syntax of fieldsDefaultPublic in example

---

docs/events/index.md

Doc grammar improvements

---

src/DependencyInjection/Configuration.php

| Fixed tickets | n/a
Upgrading to sf 4.2, you get the following deprecation:
> A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.
Show context    Hide trace
{▼
/Volumes/HD/Sites/geolid/lisa/graph/vendor/symfony/config/Definition/Builder/TreeBuilder.php:30 {▶}
/Volumes/HD/Sites/geolid/lisa/graph/vendor/overblog/graphql-bundle/src/DependencyInjection/Configuration.php:40 {▶}
Here is the fix.

Fix deprecation on symfony 4.2

---

lib/generator/.php_cs.dist
lib/generator/composer.json
lib/generator/src/ClassUtils.php
lib/generator/src/Generator/AbstractClassGenerator.php
lib/generator/src/Generator/AbstractTypeGenerator.php
lib/generator/src/Generator/TypeGenerator.php
lib/generator/tests/AbstractStarWarsTest.php
lib/generator/tests/ClassUtilsTest.php
lib/generator/tests/DateTimeType.php
lib/generator/tests/Generator/AbstractTypeGeneratorTest.php
lib/generator/tests/Generator/FooInterface.php
lib/generator/tests/Generator/FooTrait.php
lib/generator/tests/Generator/TypeGeneratorModeTest.php
lib/generator/tests/Generator/TypeGeneratorTest.php
lib/generator/tests/Resolver.php
lib/generator/tests/StarWarsData.php
lib/generator/tests/StarWarsIntrospectionTest.php
lib/generator/tests/StarWarsQueryTest.php
lib/generator/tests/TestCase.php
src/Generator/TypeGenerator.php

Migrate genrator to php7.1

---

src/Config/Processor.php
src/Config/Processor/BuilderProcessor.php
tests/DependencyInjection/Builder/BoxFields.php
tests/DependencyInjection/Builder/MutationField.php
tests/DependencyInjection/OverblogGraphQLTypesExtensionTest.php

| Fixed tickets | #290
Todo:
Todo decision making (please give your feedback on this):
**Current behavior**: override. 
**My suggetion**: Do not allow, throw exception - otherwise hard to debug issues can happen.
**Current behavior**: No, they are not processed. Those  types are "completed" as provided by the builder
**My suggestion**: Leave it this way. Prevents a lot of configuration complexity and handling of infinite recursions is not needed this way.

feature #290

---

README.md

| Fixed tickets |
Just a missing doc link

Fix readme missing link to fields builder docs

---

composer.json
src/Relay/Mutation/MutationFieldDefinition.php
tests/Relay/Mutation/MutationFieldDefinitionTest.php

The reason for this change is that when you use Symfony Expression language to configure mutation types, there is really no validation for it. If, for instance, one just passes a string without the expression trigger `@=`, the string will just be `json_encoded` and you won't end up with a valid callable, i.e.:
```
"mutation('graphql.some_mutation', [value['foo'], value['bar']])"
"{"mutation":"graphql.some_other_mutation"}"
```
(correct), versus:
```
""mutation('graphql.some_mutation', [value['foo'], value['bar']])""
```
(incorrect).
It would then not not be able to resolve the mutation response and …

Validate configuration for `MutationFieldDefinition`

---

src/Transformer/ArgumentsTransformer.php
tests/Transformer/ArgumentsTransformerTest.php

| Fixed tickets | #486
This fixes #486 by skipping object population only if the value is strictly null

Fix transforming falsy values (fixes #486)

---

src/Transformer/ArgumentsTransformer.php
tests/Transformer/ArgumentsTransformerTest.php
tests/Transformer/InputType2.php

Fix a bug in the arguments transformer when a type is non null, we must populate objects based on the wrapped type.

Handle NonNull wrapped types & add tests

---

docs/definitions/resolver-map.md
src/Config/Processor/BuilderProcessor.php
src/Definition/Argument.php
src/Definition/ArgumentFactory.php
src/Definition/ArgumentInterface.php
src/Definition/ConfigProcessor/WrapArgumentConfigProcessor.php
src/DependencyInjection/Configuration.php
src/DependencyInjection/OverblogGraphQLExtension.php
src/EventListener/TypeDecoratorListener.php
src/Generator/TypeGenerator.php
src/GraphQL/Relay/Mutation/MutationFieldResolver.php
src/Relay/Connection/ConnectionBuilder.php
src/Relay/Connection/Paginator.php
src/Resolver/Resolver.php
src/Resources/config/definition_config_processors.yml
src/Resources/config/services.yml
tests/Definition/ArgumentTest.php
tests/EventListener/TypeDecoratorListenerTest.php
tests/Functional/App/config/argumentWrapper/mapping/query.types.yml

| Fixed tickets | #326 
Allow to customize Argument class using configuration:
```yaml
overblog_graphql:
definitions:
argument_class: 'Overblog\GraphQLBundle\Definition\Argument'
```
The argument class must implement `Overblog\GraphQLBundle\Definition\ArgumentInterface`

Custom argument class

---

src/Relay/Builder/RelayConnectionFieldsBuilder.php
tests/Relay/Builder/RelayConnectionFieldsBuilderTest.php

| Fixed tickets | N/A
This PR add the missing `totalCount` mapping definition in RelayConnectionFieldsBuilder.php as discussed in https://github.com/overblog/GraphQLBundle/pull/445

Add missing totalCount on RelayConnectionFieldsBuilder

---

src/Request/Parser.php
tests/Functional/Controller/GraphControllerTest.php

Hi!
So I was reading the [serving-over-http](https://graphql.org/learn/serving-over-http/) section on graphql.org which states:
> Your GraphQL HTTP server should handle the HTTP GET and POST methods.
So I went ahead and tried using GET requests against a piece of software that uses the GraphQLBundle. For that our code returned `{"message":"The request content body must not be empty when using JSON content type request.","code":400}`.
A colleague and me searched further and ended up at `src/Request/Parser.php:33` and found that `getParsedBody` throws when the body is empty, but …

Fix body parsing for GET requests

---

src/Resources/config/aliases.yaml

| Documented?   | n/a
Fix an issue with the service `overblog_graphql.arguments_transformer` not being defined after https://github.com/overblog/GraphQLBundle/commit/9b753dcd57c9063e5fdcce1d35c317add98256dc

Add missing alias for ArgumentsTransformer

---

src/Definition/Builder/SchemaBuilder.php

| Tests pass?   | dunno
| Fixed tickets | N/A
I had a few types listed as follow:
```yaml
overblog_graphql:
definitions:
schema:
#...
types:
- Foo
```
But after some refactoring `Foo` has been changed to `Bar`. As a result the type `Foo` no longer existed and could not be loaded. Dumping the schema was resulting in a failure with the obscure error:
```
GraphQL\Error\InvariantViolation: Each entry of schema types must be instance of GraphQL\Type\Definition\Type but entry at 3 is null
```
And the trace was not much more helpful. With the following patch, the error is changed to:
```
LogicException: Could not load the type …
```

Make resolution error message clearer

---

src/DependencyInjection/Compiler/ConfigParserPass.php
src/DependencyInjection/Compiler/TypeGeneratorPass.php
src/DependencyInjection/Configuration.php
src/DependencyInjection/OverblogGraphQLExtension.php
src/OverblogGraphQLBundle.php
tests/DependencyInjection/Compiler/ConfigParserPassTest.php

| BC breaks?    | possible
This change leaves more flexibility to developers to prepend the config of the bundle without conflicting with config parsing

Move config parser to compiler pass

---

src/Transformer/ArgumentsTransformer.php
tests/Transformer/ArgumentsTransformerTest.php
tests/Transformer/InputType3.php

Fixes issue `nonNull` & `listOf` inputs not populated by `ArgumentsTransformer`
Example what did not work:
```php
/**
* @GQL\Input()
*/
final class ChangeUser
{
/**
* @GQL\Field(type="Id!")
*
* @var UuidInterface
*/
public $userId;
/**
* @GQL\Field(type="[ChangeUserOperationInput!]!")
*
* @var ChangeUserOperation[]
*/
public $operations;
}
```
Hereby `ChangeUserOperationInput` was not populated.
@Vincz 
You think **new** error raised error tests needed for this case?
With all those `field1`, `field2`, etc. its a bit hard to wrap the heard around :D. 
As an aside maybe need to …

Fix args transformer populating nonNull-listOf inputs

---

composer.json

PHPunit 8.3 is not compatible with symfony/phpunit-bridge <=4.3.3

Fix Appveyor build

---

docs/security/fields-access-control.md

Since it refers to YAML instead of annotation.

Fix typo on access control docs

---

docs/definitions/type-system/enum.md

Fixed example of Enum. 
Added public $value.
Without class attribute `$value` the Enum doesn't work.

fixed example of Enum. Added public $value.

---

.travis.yml
src/DependencyInjection/OverblogGraphQLExtension.php
src/Resources/config/services.yaml
src/Validator/ValidatorFactory.php
tests/EventListener/ValidationErrorsListenerTest.php
tests/ExpressionLanguage/ExpressionFunction/GraphQL/ArgumentsTest.php
tests/Functional/Validator/InputValidatorTest.php
tests/Transformer/ArgumentsTransformerTest.php
tests/Validator/InputValidatorTest.php
tests/Validator/Mapping/MetadataFactoryTest.php

the service `validator.validator_factory` comes with validator component so should not be required since validator itself is optional
```
The service "Overblog\GraphQLBundle\Definition\Builder\TypeFactory" has a dependency on a non-existent service "validator.validator_factory".
```

Fix @validator.validator_factory optional service

---

src/ExpressionLanguage/ExpressionFunction.php
src/ExpressionLanguage/ExpressionFunction/GraphQL/Mutation.php
src/ExpressionLanguage/ExpressionFunction/GraphQL/Relay/IdFetcherCallback.php
src/ExpressionLanguage/ExpressionFunction/GraphQL/Relay/MutateAndGetPayloadCallback.php
src/ExpressionLanguage/ExpressionFunction/GraphQL/Relay/ResolveSingleInputCallback.php
src/ExpressionLanguage/ExpressionFunction/GraphQL/Resolver.php

this remove BC on expression function in 0.13@dev

Make expression function evaluator optional

---

docs/annotations/index.md

I had some issues figuring out how the Annotations work without using any other type of mapping. It says nowhere that you would need an empty RootQuery/RootMutation.
This should clear things up.

Added a paragraph about using only Annotations as mapping type

---

src/Config/InputObjectTypeDefinition.php
src/Config/TypeWithOutputFieldsDefinition.php
tests/Functional/App/config/access/mapping/access.types.yml
tests/Functional/App/config/argumentWrapper/mapping/query.types.yml
tests/Functional/App/config/global/mapping/global.types.yml
tests/Functional/App/config/inheritance/mapping/Decorators.types.yaml
tests/Functional/App/config/inheritance/mapping/QueryHelloWord.types.yaml
tests/Functional/App/config/inheritance/mapping/Relay.types.yaml

This change allows to use short syntax for field type declarations in following types: 
- `object`
- `input-object`
- `interface`
- `relay-mutation-input`
- `relay-mutation-payload`
before:
```yml
Character:
type: interface
config:
fields:
id:
type: String!
name:
type: String
friends:
type: "[Character]"
appearsIn:
type: "[Episode]"
resolveType: "@=resolver('character_type', [value, typeResolver])"
Human:
type: object
config:
fields:
id:
type: String!
name:
type: String
friends:
type: "[Character]"
appearsIn:
type: "[Episode]!"
primaryFunction:
type: String
```
after:
```yml
Character:
type: …
```

Allow fields short syntax

---

composer.json
phpstan.neon.dist

- Update phpstan/phpstan
- Update phpstan/phpstan-phpunit
- Add phpstan/extension-installer to auto-register extensions
I have only one question, why do you chose to add the package during the composer step instead of adding it on required-dev? There are some blockers or moving in it should be accepted?

update phpstan, phpstan-phpunit and added phpstan/extension-installer

---

docs/error-handling/index.md
src/DependencyInjection/OverblogGraphQLExtension.php
src/Error/ErrorHandler.php
src/Error/ExceptionConverter.php
src/Error/ExceptionConverterInterface.php
src/EventListener/ErrorHandlerListener.php
tests/DependencyInjection/Compiler/ConfigParserPassTest.php
tests/Error/ErrorHandlerTest.php
tests/Error/ExceptionConverterTest.php

| Fixed tickets | #583
With the changes of this PR I extracted from the `ErrorHandler` class the code that maps the user exceptions to the GraphQL exception classes. This way, it's possible to map an exception to a certain other exception. Since this is an advanced use case I decided to not modify the configuration to expose this possibility, thus through it it's only possible to convert exceptions to the `UserError` or `UserWarning` classes like now

Extract the code that maps exceptions to GraphQL error classes to its own class

---

phpstan-baseline.neon
phpstan.neon.dist

- Increase phpstan level to 7
- Introduce phpstan-baseline for the current status of project
See more [here](https://medium.com/@ondrejmirtes/phpstans-baseline-feature-lets-you-hold-new-code-to-a-higher-standard-e77d815a5dff)

move phpstan to level 7 and add baseline in order to ignore errors

---

src/Config/Parser/GraphQL/ASTConverter/EnumNode.php
tests/Config/Parser/fixtures/graphql/schema-0.11.graphql
tests/Config/Parser/fixtures/graphql/schema.graphql
tests/Config/Parser/fixtures/graphql/schema.php

| Fixed tickets | #612
This PR fixes a bug that was causing the description of the enum values to be taken from the node of the enum instead of from the node of the value itself.

Fix parsing of the descriptions of the enum values when using GraphQL schema file

---

UPGRADE-0.13.md
docs/definitions/quick-start.md
docs/definitions/resolver-map.md
src/DependencyInjection/Compiler/ResolverMapTaggedServiceMappingPass.php
src/DependencyInjection/Configuration.php
src/DependencyInjection/OverblogGraphQLExtension.php
src/OverblogGraphQLBundle.php
tests/DependencyInjection/Compiler/ResolverMapTaggedServiceMappingPassTest.php
tests/Functional/App/config/schemaLanguage/config.yml

| BC breaks?    | maybe, see below
| Fixed tickets | #592
With this PR I'm going to deprecate the `overblog_graphql.definitions.schema.[...].resolver_maps` option and instead we are going to promote the use of the service tag `overblog_graphql.resolver_map`. The tag supports an optional attribute `priority` that allows specifying the priority per-schema of the resolver map

Auto-register the resolver maps using service tags

---

src/Definition/Builder/SchemaBuilder.php
src/Request/Executor.php

| Documented?   | nothing to document
Previously, running `bin/console lint:container` with this bundle installed lead to this error output:
```
Invalid definition for service "overblog_graphql.request_executor": argument 2 of "Overblog\GraphQLBundle\Request\Executor::addSchemaBuilder" accepts "callable", "Closure" passed.
```
This fixes this error by passing `\Closure` from `\Overblog\GraphQLBundle\Definition\Builder\SchemaBuilder::getBuilder` to `Executor::addSchemaBuilder`.

Update return typehint for SchemaBuilder

---

src/Resolver/AccessResolver.php

| BC breaks?    | could be, if people use `"true"` instead of `true`
| Fixed tickets | #635
This fixes #635
When you provide an expression inside the `access` option, it will only work as an expression when you prefix it with `@=`. When you forget to do this, it will be just a string.
Previously, the code would check if the access value is trueish instead of strict true. This granted access to all fields that had mistakenly forgotten to prefix with `@=`.
I also flipped the if statement so that it's much easier to parse as a human :D

Only grant permission when `access` returns true

---

src/Resolver/FieldResolver.php

When upgrading to 13.1 my API broke: all of a sudden, some fields were `null` instead of their actual value.
The problem is inside the FieldResolver, it does not handles methods with no leading `get` prefix. In my case my entity looks like this:
```php
class Entity
{
public function hasSomething() {
//...
}
}
```
And the schema:
```yaml
Entity:
type: object
config:
fields:
hasSomething:
type: "Boolean"
```
We want to call `$entity->hasSomething()` during resolution, not only `$entity->getHasSomething()`.

Added support for getters with no prefix on FieldResolver

---

src/EventListener/ErrorLoggerListener.php
tests/EventListener/ErrorLoggerListenerTest.php

I noticed that most of the Monolog default handlers uses the `exception` key instead of `throwable` to retrieve the exception from the context data of a log, thus with this PR I'm gonna fix the `ErrorLoggerListener` listener. Here a list of handlers that make this assumption:
- Sentry handler (both v1 and v2)
- Rollbar handler
- New Relic handler
To not break BC both keys could be used and in the next major version the old one could be dropped. Let me know how you want to proceed, and if you want of course.

Use the exception key in the context of the logger

---

UPGRADE-1.0.md
docs/helpers/relay-paginator.md
phpstan-baseline.neon
src/Relay/Connection/ConnectionBuilder.php
src/Relay/Connection/Cursor/Base64CursorEncoder.php
src/Relay/Connection/Cursor/Base64UrlSafeCursorEncoder.php
src/Relay/Connection/Cursor/CursorEncoderInterface.php
src/Relay/Connection/Cursor/PlainCursorEncoder.php
src/Util/Base64Encoder.php
tests/Relay/Connection/AbstractConnectionBuilderTest.php
tests/Relay/Connection/ConnectionBuilderTest.php
tests/Relay/Connection/Cursor/Base64CursorEncoderTest.php
tests/Relay/Connection/Cursor/Base64UrlSafeCursorEncoderTest.php
tests/Relay/Connection/Cursor/PlainCursorEncoderTest.php
tests/Util/Base64EncoderTest.php
tests/Util/Base64UrlSafeEncoderTest.php

Sometimes it's useful to change the way the cursor of the edges of a connection are encoded/decoded, e.g. in the tests or if base64 is not the format users want to use for their applications. With this PR the `ConnectionBuilder` now accepts a new parameter that allows such customization. I chose to put the parameter as first rather that as the last (sadly breaking BC) because I think that even if rare it's probably more common the willing of changing how the cursor is encoded instead of how the edges or the connection itself are built, but of course this can be re-evaluated.

Make the encoder for the cursors of the edges of a connection customizable

---

src/Definition/ConfigProcessor/AclConfigProcessor.php
src/Definition/ConfigProcessor/PublicFieldsFilterConfigProcessor.php
src/Definition/ConfigProcessor/WrapArgumentConfigProcessor.php

Fix the bug preventing use of shorthand field definitions described [here](https://webonyx.github.io/graphql-php/type-system/object-types/) (section **Shorthand field definitions**)

Fix shorthand field definitions feature

---

README.md
composer.json
docs/profiler/index.md
phpstan-baseline.neon
src/Controller/ProfilerController.php
src/DataCollector/GraphQLCollector.php
src/DependencyInjection/Configuration.php
src/DependencyInjection/OverblogGraphQLExtension.php
src/Event/ExecutorArgumentsEvent.php
src/Event/ExecutorResultEvent.php
src/Request/Executor.php
src/Resources/config/profiler.yaml
src/Resources/views/profiler/graphql.html.twig
src/Resources/views/profiler/panel.html.twig
tests/Controller/ProfilerControllerTest.php
tests/DataCollector/GraphQLCollectorTest.php
tests/Request/ExecutorTest.php

| Bug fix?      | yes/no
| Deprecations? | o
| Fixed tickets | #555
The profiler feature

Profiler feature

---

src/ExpressionLanguage/ExpressionFunction/DependencyInjection/Parameter.php
src/ExpressionLanguage/ExpressionFunction/DependencyInjection/Service.php
src/ExpressionLanguage/ExpressionFunction/GraphQL/Arguments.php
src/ExpressionLanguage/ExpressionFunction/Security/GetUser.php
src/ExpressionLanguage/ExpressionFunction/Security/HasAnyPermission.php
src/ExpressionLanguage/ExpressionFunction/Security/HasAnyRole.php
src/ExpressionLanguage/ExpressionFunction/Security/HasPermission.php
src/ExpressionLanguage/ExpressionFunction/Security/HasRole.php
src/ExpressionLanguage/ExpressionFunction/Security/IsAnonymous.php
src/ExpressionLanguage/ExpressionFunction/Security/IsAuthenticated.php
src/ExpressionLanguage/ExpressionFunction/Security/IsFullyAuthenticated.php
src/ExpressionLanguage/ExpressionFunction/Security/IsGranted.php
src/ExpressionLanguage/ExpressionFunction/Security/IsRememberMe.php
src/Validator/Constraints/ExpressionValidator.php
tests/ExpressionLanguage/ExpressionFunction/DependencyInjection/ParameterTest.php
tests/ExpressionLanguage/ExpressionFunction/DependencyInjection/ServiceTest.php
tests/ExpressionLanguage/ExpressionFunction/GraphQL/ArgumentsTest.php
tests/ExpressionLanguage/ExpressionFunction/Security/GetUserTest.php
tests/ExpressionLanguage/ExpressionFunction/Security/HasAnyPermissionTest.php
tests/ExpressionLanguage/ExpressionFunction/Security/HasAnyRoleTest.php
tests/ExpressionLanguage/ExpressionFunction/Security/HasPermissionTest.php
tests/ExpressionLanguage/ExpressionFunction/Security/HasRoleTest.php
tests/ExpressionLanguage/ExpressionFunction/Security/IsAnonymousTest.php
tests/ExpressionLanguage/ExpressionFunction/Security/IsAuthenticatedTest.php
tests/ExpressionLanguage/ExpressionFunction/Security/IsFullyAuthenticatedTest.php
tests/ExpressionLanguage/ExpressionFunction/Security/IsGrantedTest.php
tests/ExpressionLanguage/ExpressionFunction/Security/IsRememberMeTest.php
tests/Functional/App/config/validator/config.yml

| Fixed tickets | #588 
As mentioned in comment https://github.com/overblog/GraphQLBundle/issues/588#issuecomment-610393275 the true problem behind issue #588 is that the setup of the expression language functions is flawed. The expression language functions are not designed to take services as constructor arguments. Instead they must rely on dependencies passed into the function during execution.
This PR fixes these issues with several expression language functions. Instead of passing dependencies to the constructor (from where they were injected into closures), the evaluators no rely on the …

Changes setup of expression language functions to fix issue #588

---

src/Definition/ConfigProcessor/AclConfigProcessor.php
src/Generator/TypeBuilder.php

The `useStrictAccess` is a boolean option on GraphQL types. It is `true` by default. There is no need to render both states (true and false), so this PR changes it: it will be rendered only if set to `false`. If it's not defined, it will be considered as `true`.
Here is an example of an object type:
```php
final class HumanType extends ObjectType implements GeneratedTypeInterface
{
public const NAME = 'Human';
public function __construct(ConfigProcessor $configProcessor, GlobalVariables $globalVariables = null)
{
$configLoader = fn() => [
'name' => self::NAME,
'description' => 'A humanoid creature in the Star Wars …
```

Treat `useStrictAccess` option as true by default

---

UPGRADE-1.0.md
src/Definition/Argument.php
src/Definition/ArgumentInterface.php
tests/Functional/App/config/access/mapping/access.types.yml

This PR adds a magic `__get` method to the `Argument` class, to allow a cleaner syntax in the expressions.
Instead of this:
```console
@=res('my_resolver', [args['firstName'], args['lastName']])
```
We can write this:
```console
@=res('my_resolver', [args.firstName, args.lastName])
```
which is obviously easier to read and is shorter.
And inside resolvers user can do `$args->firstName`, ``$args->lastName``

Allow cleaner access syntax in expressions

---

src/Config/Parser/AnnotationParser.php
src/DependencyInjection/OverblogGraphQLExtension.php
tests/EventListener/ValidationErrorsListenerTest.php
tests/ExpressionLanguage/ExpressionFunction/GraphQL/ArgumentsTest.php
tests/Functional/Validator/InputValidatorTest.php
tests/Transformer/ArgumentsTransformerTest.php
tests/Validator/InputValidatorTest.php
tests/Validator/Mapping/MetadataFactoryTest.php

Simplify FQCN when using class_exists

---

docs/annotations/annotations-reference.md
docs/definitions/type-system/object.md
docs/definitions/type-system/union.md
src/Annotation/Mutation.php
src/Annotation/Type.php
src/Annotation/Union.php
src/Config/Parser/Annotation/GraphClass.php
src/Config/Parser/AnnotationParser.php
src/DependencyInjection/OverblogGraphQLExtension.php
tests/Config/Parser/AnnotationParserTest.php
tests/Config/Parser/fixtures/annotations/Invalid/InvalidProvider.php
tests/Config/Parser/fixtures/annotations/Repository/PlanetRepository.php
tests/Config/Parser/fixtures/annotations/Type/Armored.php
tests/Config/Parser/fixtures/annotations/Type/Droid.php
tests/Config/Parser/fixtures/annotations/Type/Hero.php
tests/Config/Parser/fixtures/annotations/Type/Mandalorian.php
tests/Config/Parser/fixtures/annotations/Type/RootMutation2.php
tests/Config/Parser/fixtures/annotations/Type/RootQuery2.php
tests/Config/Parser/fixtures/annotations/Type/Sith.php
tests/Config/Parser/fixtures/annotations/Union/Killable.php
tests/EventListener/ValidationErrorsListenerTest.php
tests/ExpressionLanguage/ExpressionFunction/GraphQL/ArgumentsTest.php
tests/Functional/Validator/InputValidatorTest.php
tests/Transformer/ArgumentsTransformerTest.php
tests/Validator/InputValidatorTest.php
tests/Validator/Mapping/MetadataFactoryTest.php

| Documented?   | not yet
- Annotations Refactoring (with a GraphClass)
- Add missing `isTypeOf` on `@GQL\Type`
- Add `targetType` on `@GQL\Mutation` to handle multiple schema #526
- Autodiscover Interfaces for `@GQL\Type` based on PHP interfaces or parent classes #701
- Autodiscover Union types for `@GQL\Union` based on PHP interfaces or children classes #701

Annotations refactoring

---

docs/annotations/annotations-reference.md
docs/definitions/schema.md
src/Config/Parser/AnnotationParser.php
src/DataCollector/GraphQLCollector.php
src/Event/ExecutorArgumentsEvent.php
src/Request/Executor.php
src/Resources/views/profiler/graphql.html.twig
tests/DataCollector/GraphQLCollectorTest.php

- Add schemaName in the ExecutorArgumentsEvent
- Make the GraphQL collector retrieve schema from ExecutorArgument instead of routing
- Consider default schema as the one with name 'default' or the first one defined
- Apply same logic to Annotation Parser
- Update doc
| Fixed tickets | #608, #712

Add schema name as Executor argument & fix default schema

---

src/DependencyInjection/Configuration.php

| Fixed tickets | #714
Fix issue #714
@mcg-web should also be applied to 0.11 and 0.12

Fix issue #714

---

docs/definitions/type-system/enum.md
src/Config/Parser/YamlParser.php
tests/Config/Parser/Constants.php
tests/Config/Parser/YamlParserTest.php
tests/Config/Parser/fixtures/annotations/Enum/Race.php
tests/Config/Parser/fixtures/yaml/constants.yml

| Fixed tickets | #303, #304
I would like to add "more native" support for PHP constants in YAML files by enabling the `!php/const` tag. 
I struggled a bit while creating my first GraphQL project today, because I expected this feature to be available. Also this way the constants don‘t need to be fetched during runtime with the PHP function `\constant()`.
This topic was already discussed in #303 but closed because of inactivity.

Add more native support for php constants in yaml files

---

UPGRADE-0.13.md
src/Resolver/FieldResolver.php
tests/Resolver/ResolverFieldTest.php
tests/Resolver/Toto.php

| Deprecations? | yes/no
I'm updating from 0.11 to 0.13 on our big app at work, and we have a lot of errors on fields which depend of isser methods.
Isser methods support has been removed in 0.13, because the Symfony PropertyAccessor has been removed too, due to performance issue for large schema.
However, I think it can be nice to re-add a basic support out-of-the-box for issers.
What do you think?
Thanks!

fix(field-resolver): re-add support for isser methods

---

docs/annotations/annotations-reference.md
src/Annotation/Mutation.php
src/Annotation/Query.php
src/Config/Parser/AnnotationParser.php
tests/Config/Parser/AnnotationParserTest.php
tests/Config/Parser/fixtures/annotations/Repository/PlanetRepository.php

| Fixed tickets | #725  
Allow to target multiple types with `@Query` & `@Mutation` annotations.

Allow multiple target types

---

.php_cs.dist
phpstan-baseline.neon
src/Annotation/Access.php
src/Annotation/Arg.php
src/Annotation/Deprecated.php
src/Annotation/Description.php
src/Annotation/Enum.php
src/Annotation/EnumValue.php
src/Annotation/Field.php
src/Annotation/FieldsBuilder.php
src/Annotation/Input.php
src/Annotation/IsPublic.php
src/Annotation/Mutation.php
src/Annotation/Provider.php
src/Annotation/Query.php
src/Annotation/Relay/Connection.php
src/Annotation/Relay/Edge.php
src/Annotation/Scalar.php
src/Annotation/Type.php
src/Annotation/TypeInterface.php
src/Annotation/Union.php
src/Config/Parser/Annotation/GraphClass.php
src/Config/Parser/AnnotationParser.php

@Vincz please check the PR carefully, because I don't know everything, that happens in your code, therefore could make mistakes. I just added type-hints to annotation classes and made general changes in the annotation related code. Ask if you have any questions.

Add type-hints in annotation classes

---

src/Transformer/ArgumentsTransformer.php

Reverts overblog/GraphQLBundle#656

Revert "Allow to use non-empty constructor for input types"

---

.dockerignore
Dockerfile

| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | yes/no
| Deprecations? | yes/no

Make the docker image more usable

---

src/Annotation/Union.php

`@GQL\Union(types)` isn't required anymore as the `types` can be auto-guessed.

Fix annotation on master

---

src/Generator/TypeGenerator.php

| Fixed tickets | #744 
Fix the bug described in issue #744

Fix generation of last comma in arrays

---

docs/annotations/index.md
src/Config/Parser/AnnotationParser.php
tests/Config/Parser/AnnotationParserTest.php
tests/Config/Parser/fixtures/annotations/Input/Planet.php
tests/Config/Parser/fixtures/annotations/Type/Droid.php
tests/Config/Parser/fixtures/annotations/Type/Lightsaber.php

- Skip properties without a Field annotation
- Enable field type guessing for Input annotation

Fix Input Field annotations handling

---

src/Command/GraphQLDumpSchemaCommand.php

baseExportPath already point to var dir

---

src/Config/Parser/AnnotationParser.php
tests/Config/Parser/fixtures/annotations/Input/Planet.php

Based on the unittest this is a fix

Really ignore field and not create an empty InputType

---

docs/annotations/annotations-reference.md
src/Annotation/Mutation.php
src/Annotation/Provider.php
src/Annotation/Query.php
src/Config/Parser/AnnotationParser.php
tests/Config/Parser/AnnotationParserTest.php
tests/Config/Parser/fixtures/annotations/Repository/PlanetRepository.php
tests/Config/Parser/fixtures/annotations/Repository/WeaponRepository.php

This PR adds attributes `targetTypeQuery` and `targetTypeMutation` on `@Provider`
It will be used as default `targetType` for `@Query` or `@Mutation` if it is not set.

Add attributes `targetTypeQuery` and `targetTypeMutation` on `@Provider`

---

src/Validator/InputValidator.php

I was having this example:
```yaml
Mutation:
type: object
config:
fields:
create:
type: "Ladder!"
resolve: "@=mutation('LadderCreate', [args, context, validator])"
access: '@=isAuthenticated()'
args:
input:
type: "LadderInput!"
validation: cascade
LadderInput:
type: input-object
config:
fields:
name:
type: String!
validation:
- NotBlank: ~
- Length:
min: 10
max: 100
matchesSystem:
type: "[MatchesSystemEnum!]!"
```
I.e. the `matchesSystem` field in `LadderInput` had no `validation`, so the `InputValidator.php` was crashing as it had no `$inputField->config['validation']`. Probably the default value should be an empty array.
| Documented?   | …

Fixed a bug on validating fields when validation is cascade

---

.php_cs.dist
src/Error/InvalidArgumentError.php
src/Error/InvalidArgumentsError.php
src/Error/UserErrors.php
src/ExpressionLanguage/ExpressionFunction/Security/Helper.php
src/ExpressionLanguage/ExpressionLanguage.php
src/Generator/Converter/ExpressionConverter.php
src/Generator/TypeBuilder.php

- Add extended PHPDocs with code examples to each method of TypeBuilder
- Disable PHP-CS-Fixer rule to add unnecessary dots (they were added even after `:`
- Create static method `ExpressionLanguage::isStringWithTrigger`
- Other minor changes

Refactor TypeBuilder and resolve some todos

---

src/Controller/ProfilerController.php
tests/Controller/ProfilerControllerTest.php

[Symfony Profiler](https://symfony.com/doc/current/profiler.html) generates and saves profiles on every request. Every profile object contains a list of `DataCollector`'s, that were used to create it. If for some reason your project contains a profile, that was generated before the `GraphQLCollector` was introduced, it will throw an error, when you open the GraphQL tab in the Profiler, because it tries to iterate over all generated profiles and use a GraphQLCollector object, which doesn't exist.
This PR also replaces deprecated test methods with new ones.

Fix Profiler bug

---

src/Generator/TypeBuilder.php
src/Resolver/TypeResolver.php
tests/Resolver/TypeResolverTest.php

| Fixed tickets | webonyx/graphql-php#425, webonyx/graphql-php#557
As described here webonyx/graphql-php#425, instantiating schemas with many types can hit performance. It was suggested (and implemented) to wrap field type definitions into a closure for [lazy loading](https://en.wikipedia.org/wiki/Lazy_loading).
This PR updates the `TypeBuilder` class to generate proper field types. It wraps only user-defined types into a closure.
Example:
```php
$config = [
'fields' => fn() => [
'street' => Type::nonNull(Type::string()),
'city' => Type::nonNull(Type::string()),
'zipCode' => Type::nonNull(Type::int()),
'period' => fn() => …
```

Update generated types

---

src/Relay/Connection/ConnectionInterface.php
src/Relay/Connection/Output/Connection.php

An error occurs when trying to return a promise to totalCount
| Fixed tickets | #286 

Made it possible for totalCount to be a promise

---

src/Resolver/FieldResolver.php

Made changes to the default field resolver:
- #### 1. Replace `self` with `static` for a better extensibility
- #### 2. Add checking of getters that start with `has` prefix (like in [PropertyAccess](https://symfony.com/doc/current/components/property_access.html#using-hassers-issers))
- #### 3. Reduce function calls (micro-optimisation):
This call: 
```php
str_replace(' ', '', ucwords(str_replace('_', ' ', $fieldName)))
```
is equal to this: 
```php
str_replace('_', '', ucwords($fieldName, '_'))
```
Additionally, PHP method names are case-insensitive, which means it is not required to call `ucwords`. In other words these …

Refactor default field resolver

---

src/Controller/GraphController.php

| Tests pass?   | n/a - I haven't been able to do this yet, will try to shortly
| Fixed tickets | #789 
The operationName is not passed when using the batch endpoint. It seems the code as it is explicitly passes the query and the variables, and this fix instead passes all elements of the query through. I think this is simpler - but I'm concerned I may be missing something as to why they are explicitly passed. 
The alternative would be as follows:
```
->execute($schemaName, ['query' => $query['query'], 'variables' => $query['variables'], 'operationName' => $query['operationName'])
```
I would welcome feedback from someone …

Fixes #789 - pass the full query to the executor

---

src/Transformer/ArgumentsTransformer.php
tests/Transformer/ArgumentsTransformerTest.php

| RFC? | yes
| Version       | 0.13.5
When i use annotation to map argument as "Non-nullable array of non-nullable values" the scheme is built correctly. But i got error during query execution:
`GraphQL\Error\InvariantViolation: Type loader is expected to return type "Int!", but it returned ""[0]`
Example of mapping:
```php
/**
* @GQL\Query(type="[Order]", name="order",
*     args={
*         @GQL\Arg(name="orderIds", type="[Int!]!"),
*     }
* )
*/
public function getOrders(array $orderIds): Promise
{
...
}
```

Fix annotation for non-nullable array of non-nullable values as query argument

---

src/DependencyInjection/OverblogGraphQLExtension.php

| Fixed tickets | #802
The third argument for `Overblog\GraphQLBundle\Error\ErrorHandler` is the default
message to use when an error happens. As described in the documentation
`overblog_graphql.errors_handler.internal_error_message` can be used to set a
custom message.

[0.13] Make sure that internal_error_message is used during ErrorHandler initialization

---

lib/generator/src/ClassUtils.php
lib/generator/tests/ClassUtilsTest.php

PHP 8 has a stricter type definition for the third argument of `preg_replace_callback`:
`preg_replace_callback(): Argument #3 ($subject) must be of type array|string, null given`

Fix 0.13 calling preg_replace_callback with a NULL argument in PHP 8

---

composer.json
src/Config/InterfaceTypeDefinition.php
tests/Functional/App/config/global/config.yml
tests/Functional/Command/fixtures/schema.descriptions.json
tests/Functional/Relay/Node/GlobalTest.php

| Fixed tickets | https://github.com/graphql/graphql-spec/pull/373
According to the GraphQL Specification update, interfaces can implement other interfaces. The webonyx/graphql-php already implemented it in 14.5.0 (https://github.com/webonyx/graphql-php/pull/740). This PR makes corresponding changes.

Allow interfaces implement interfaces

---

src/Request/Parser.php

| Bug fix?      | maybe
Starting since symfony 5.2 accessing non-scalar parameters via `$request->query->get()` is deprecated and will throw an exception in symfony 6. This PR fixes deprecation warning and provides forward compatibility with symfony 6

Forward compatibility with symfony 6 at Parser

---

src/Config/Processor/InheritanceProcessor.php

| Fixed tickets | #831
Fixes a deprecation on PHP 8.0:
> uksort(): Returning bool from comparison function is deprecated, return an integer less than, equal to, or greater than zero
This targets `0.12` as the `uksort()` call was introduced in this branch.
Not sure why all tests fail: failures are unrelated to this commit (I tried reverting it, same result).

Fix uksort() callback returning bool deprecation

---

docs/error-handling/index.md
src/DependencyInjection/Configuration.php

Since https://github.com/overblog/GraphQLBundle/pull/803, the example here results in runtime error due to the fact that internal_error_message in `ErrorHandler::__construct` is non-nullable.

Fix error handler configuration example

---

.github/workflows/ci.yml
composer.json

see https://github.com/shivammathur/setup-php/issues/452

Bump ci ubuntu version to fix setup-php build

---

.github/workflows/ci.yml
tests/Functional/TestCase.php

Fix ci builds

---

src/Executor/Promise/Adapter/ReactPromiseAdapter.php

See https://github.com/webonyx/graphql-php/blob/master/src/Executor/Promise/Adapter/ReactPromiseAdapter.php
This makes it possible to use the bundle together `dev-master`.

Make ReactPromiseAdapter compatible with webonyx master

---

src/Request/Executor.php

This allows the bundle to use the latest webonyx dev version.
The experimental executor has been removed in Webonyx because it didn't give much advantages. 
To make it possible to run this bundle with the latest dev version of Webonyx we now first check if the experimental executor still exists, before trying to enable it.

Check if experimental executor exists before trying to set it

---

src/Command/DebugCommand.php

| Fixed tickets | N/A
In one of our projects, we decorate `QueryResolver` and `MutationResolver` for our needs.
But currently, the `DebugCommand` depends on concrete implementations instead of interfaces.
So when we run the `bin/console list`, Symfony crash because of the dependency injection.
This PR updates the `DebugCommand` constructor to inject `FluentResolverInterface` instead of concrete implementations.

Fix DebugCommand dependency injection

---

src/EventListener/RequestFilesListener.php

| BC breaks?    |no
Since all GraphQL operations are (mostly) always bound to a request lifecycle it makes sense to expose the request in the context.
This saves implementors from querying the RequestStack to get the request.

Expose `request` in context

---

.github/workflows/ci.yml

It's important to run PHPStan on all supported PHP versions.
On PHP 8.0 it detects other issues.
When this is merged, we can fix the PHP 8 issues.
See #908

Run PHPStan on 7.4 and 8.0

---

.github/workflows/ci.yml

This makes the output very noisy. I think this was left over from the migration to GH Actions. Not needed anymore.

PHPUnit > Disable verbose / debug mode

---

src/Command/DebugCommand.php

Debug command depends on interface rather on implementations

---

src/Generator/TypeBuilder.php

| Bug fix?      |no
| Deprecations? | ?
I noticed that types generated by `graphql:compile` don't include the `AliasedInterface`. This is weird, because in my YAML definition I reference everything with aliases.

Always compile types with `AliasedInterface`

---

src/OverblogGraphQLBundle.php

| Fixed tickets | https://github.com/overblog/GraphQLBundle/issues/896
This PR solves the issue where our container compilation fails because of a missing compiler pass

#896: Removed deprecated compiler pass.

---

.github/workflows/ci.yml
composer.json

Forgot to pass the value to composer install.

Fix `highest/lowest`

---

.github/workflows/ci.yml
composer.json
tests/Functional/App/TestKernel.php

This disables the default HttpKernel Logger that writes to stdout.
Gives a much cleaner output.

Enable MonologBundle in functional tests

---

.github/workflows/ci.yml

Use php-coveralls.phar instead of global composer installation

---

src/OverblogGraphQLBundle.php

Updating to Symfony 5.4 + PHP 8.0, I get the following warning:
```
User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::getContainerExtension()" might add "?ExtensionInterface" as a native return type declaration in the future. Do the same in child class "Overblog\GraphQLBundle\OverblogGraphQLBundle" now to avoid errors or add an explicit @return annotation to suppress this message.
```
| Fixed tickets | -

Add type on `getContainerExtension` for future compat

---

.github/workflows/ci.yml

This is the recommended way to pin everything to the same major.minor. 
Without it, it will still install other packages.

Use Flex to require specific Symfony versions

---

src/Annotation/Access.php
src/Annotation/Arg.php
src/Annotation/ArgsBuilder.php
src/Annotation/Builder.php
src/Annotation/Deprecated.php
src/Annotation/Description.php
src/Annotation/Enum.php
src/Annotation/EnumValue.php
src/Annotation/Field.php
src/Annotation/FieldBuilder.php
src/Annotation/FieldsBuilder.php
src/Annotation/Input.php
src/Annotation/IsPublic.php
src/Annotation/Mutation.php
src/Annotation/Provider.php
src/Annotation/Query.php
src/Annotation/Relay/Connection.php
src/Annotation/Relay/Edge.php
src/Annotation/Scalar.php
src/Annotation/Type.php
src/Annotation/TypeInterface.php
src/Annotation/Union.php

Also fixed a problem that will pop-up in PHP 8.1 with the `TypeInterface`:
In PHP 8.1 optional parameters cannot be defined before required parameters.
Because `string name = null` is optional, we also have to make `string $resolveType` optional. This way it works on PHP 8.1 without breaking BC.
In 1.0, we should change the order.

Replace deprecated `NamedArgumentConstructorAnnotation` with `@NamedArgumentConstructor` + Address one PHP 8.1 deprecation

---

src/CacheWarmer/CompileCacheWarmer.php
src/DataCollector/GraphQLCollector.php
src/DependencyInjection/TypesConfiguration.php
src/Error/UserWarning.php
tests/Config/Parser/AttributeParserTest.php
tests/ExpressionLanguage/ExpressionFunction/Security/GetUserTest.php
tests/Functional/TestCase.php

Please review commit by commit. Nice to clean this up a bit and suppress the noise in the PHPUnit log.

Fix a bunch of deprecations

---

phpstan-baseline.neon
src/DependencyInjection/Compiler/TypeGeneratorPass.php

By manually constructing the `TypeGenerator` in `TypeGeneratorPass` we gain performance
benefits because we don't have the boot the whole container while we are in fact compiling
the container.
The container should not be used in compiler passes:
> As a rule, only work with services definition in a compiler pass and do not create service instances. In practice, this means using the methods has(), findDefinition(), getDefinition(), setDefinition(), etc. instead of get(), set(), etc.
Fixes 899

Do not use container in compiler passes

---

composer.json

This is a new feature available in Composer 2.2.0-RC1
You need to specify which plugins you allow to run. These are used in this project so we need to add them.

Add `allow-plugins` to composer schema

---

src/Definition/ConfigProcessor.php
src/Definition/GraphQLServices.php

This way, PHPStan knows that input becomes output.
Example, not PHPStan understands this:
```php
/**
* @phpstan-import-type ObjectConfig from ObjectType
*/
final class MYType extends ObjectType implements AliasedInterface
{
public function __construct(ConfigProcessor $processor, GraphQLServiceLocator $locator)
{
/**
* @var ObjectConfig $config
*/
$config = [
'name' => self::NAME,
'fields' => fn () => [
'id' => [
'type' => Type::nonNull(Type::id()),
],
],
'interfaces' => fn () => [
$locator->getType(NodeType::class),
],
];
parent::__construct($processor->process($config));
}
}
```

Add PHPStan configuration for `ConfigProcessor::process`

---

src/Definition/Type/CustomScalarType.php

After testing latest dev-master I noticed an issue with `scalarType` being required. This was never the case, I just refactored that wrong previously.
Refactored the code a bit to make it easier to read.

CustomScalarType > Make `scalarType` optional again

---

src/Generator/TypeBuilder.php
tests/Functional/App/Validator/CustomValidator1/Constraint.php
tests/Functional/App/Validator/CustomValidator2/Constraint.php
tests/Functional/App/Validator/MockValidator.php
tests/Functional/App/config/conflictingValidatorNamespaces/config.yml
tests/Functional/App/config/conflictingValidatorNamespaces/mapping/Mutation.types.yml
tests/Functional/Generator/TypeGeneratorTest.php

Closes #863
Use alias for Symfony constraints.
Use FQCN for custom validators.
| Fixed tickets | #863

Fix validation constraints namespace conflicts in generated definition files

---

src/EventListener/TypeDecoratorListener.php
tests/EventListener/TypeDecoratorListenerTest.php

This PR adds support for the new feature merged in webonyx/graphql-php#1040.
It allows returning enum values by closure and/or generator.
While working on this I also noticed that the object decorator doesn't work properly when the objects fields are returned by a generator. That's now fixed as well.
I had to add a PHPStan ignore line because of this issue: https://github.com/webonyx/graphql-php/issues/1041

Support defining enum values by callable and/or generator

---

src/Definition/ConfigProcessor.php

This makes it possible to initialize a `ConfigProcessor` that has no processors.
Solves this error:
Typed property Overblog\GraphQLBundle\Definition\ConfigProcessor::$processors must not be accessed before initialization.

Define default value for `$processors`

---

src/Generator/TypeBuilder.php
tests/Functional/App/config/typeShorthand/config.yml
tests/Functional/App/config/typeShorthand/mapping/schema.types.yml
tests/Functional/TypeShorthand/TypeShorthandTest.php

| Fixed tickets | #973
Building type with fields using shorthand type is not completely supported right now. I revert this change right now to quick fix this bug.

Add type shorthand failling test

---

src/Generator/TypeBuilder.php

Fix for https://github.com/overblog/GraphQLBundle/issues/991
| Fixed tickets | https://github.com/overblog/GraphQLBundle/issues/991

Fix type generation for Composite symfony validator with explicit 'constraints' key

---

src/Event/ExecutorArgumentsEvent.php

In relation to #1028.
- Changed the typing and PhpDocs related to `ExecutorArgumentsEvent::$rootValue` property to `mixed`<br> (as PHP is set to v8.0 which supports this type).
- Changed `new static();` to `new self();` as the `ExecutorArgumentsEvent` class is `final`
The target branch is `0.15` as it is the latest stable branch. Can be merged to `dev-master` if more properly (I don't know the process 😅).

Fixed `rootValue` typing in `ExecutorArgumentsEvent` class.

---

phpstan-baseline.neon
src/Relay/Connection/ConnectionBuilder.php
src/Relay/Connection/ConnectionInterface.php
src/Relay/Connection/EdgeInterface.php
src/Relay/Connection/Output/Connection.php
src/Relay/Connection/Output/Edge.php
src/Resolver/AccessResolver.php

By making the `ConnectionBuilder` class a generic type, the static analysis tools will understand that the outputted `ConnectionInterface` contains a list of nodes of the expected type, augmenting the IDE completion and ensuring correctness of the code upstream. I wasn't sure about the target branch to submit the change to, so if I have to change it just ask and I will do it.

Make the `ConnectionBuilder` class a generic type

---

src/Generator/TypeGenerator.php

Closes #1060 
| Fixed tickets | #1060
File permission passed to the file saving method.

Fixed not providing file permissions while saving files.

---

src/Transformer/ArgumentsTransformer.php
tests/Definition/Type/PhpEnumTypeTest.php
tests/Relay/Connection/ConnectionBuilderTest.php
tests/Transformer/ArgumentsTransformerTest.php
tests/Transformer/InputType1.php

When data for an input doesn't exist (ie. The property is not set in the data), use the default value of the input property or null if is doesn't have one.
When a input object is used in conjunction with the `ArgumentsTransformer`, if the data doesn't contain the property, use the default one from the input object instead of null.
For example:
```php
<?php
final class MyInput
{
public $field1;
public $field2 = "default_me";
}
?>
```
If the submitted `data` doesn't include the `field2` property, the input instance will be left untouched and `$field2` will equals `default_me` instead of `null`.

Fix tests & arguments transformer when data is not set

---

docs/definitions/mutation.md

| Fixed tickets | #1044 
Fix incorrect syntax for passing mutation arguments

[Doc] Fix incorrect syntax for passing mutation arguments

---

src/Controller/ProfilerController.php
src/Validator/ValidationNode.php

Fix Deprecation warnings for PHP 8.2

Fix Deprecation warning for PHP 8.2

---

.github/workflows/ci.yml

Upgrade
- runner images
- actions
- php-coveralls

Upgrade CI workflow

---

src/Transformer/ArgumentsTransformer.php
tests/Transformer/ArgumentsTransformerTest.php
tests/Transformer/InputType1.php

| Fixed tickets | #1073
Fixes https://github.com/overblog/GraphQLBundle/pull/1073#issuecomment-1759508677
The change did not consider typed properties without default value. This actually breaks existing application when upgrading to v1.0.

Fix argument transformer for typed properties without default value

---

.github/workflows/ci.yml
composer.json
src/Config/TypeDefinition.php
src/Controller/ProfilerController.php
src/Relay/Connection/ConnectionInterface.php
src/Relay/Connection/Output/PageInfo.php
src/Relay/Connection/PageInfoInterface.php
src/Resolver/TypeResolver.php
src/Resources/config/profiler.yaml
src/Upload/Type/GraphQLUploadType.php
src/Validator/InputValidator.php
tests/Config/Parser/fixtures/graphql/schema.php
tests/Controller/ProfilerControllerTest.php

This fix the problem with the profiler if the schema doesn't have a subscription. 
It's related to https://github.com/overblog/GraphQLBundle/issues/1112 and the fact that Webonyx expects `null` from not found type with the `TypeResolver` while we raise an exception.

Fix profiler & update phpcs

---

src/Config/Parser/MetadataParser/MetadataParser.php
tests/Config/Parser/MetadataParserTest.php
tests/Config/Parser/fixtures/annotations/Type/Battle.php

| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | yes/no
When a single argument is described with `#[GQL\Arg]` all other are not guessed anymore
This commit starts by guessing all arguments and override the ones that have `#[GQL\Arg]` attributes describing them
I'm not sure of a few things:
* should the type specified in the attribute override the one that was guessed?
* same for the default
* Is there cases where guessing could fail and adding the #[GQL\Arg] attribute was a way to prevent guessing failing / crashing?
in the future it would be nice if we could add the attribute on the argument directly instead of the …

Merge guessed argument properties and args described with GQL\Arg

---

docs/security/fields-public-control.md

In Symfony 6+ `security.authorization-checker` is not a public service anymore, hence the previous example won't work.
However the expression language supports using `isGranted` directly hence I propose to update the documentation.

Do not inject the authorization checker service in GraphQL types

---

src/Config/Parser/AttributeParser.php

This make the code slightly more efficient as it avoids instantiating unrelated attributes and also prevents crashes in case some attributes cannot be instantiated

Only look at attributes implementing Annotation

---

docs/annotations/annotations-reference.md
docs/annotations/arguments-transformer.md
docs/annotations/index.md
src/Annotation/Arg.php
src/Annotation/InputField.php
src/Annotation/TypeInterface.php
src/Config/Parser/MetadataParser/ClassesTypesMap.php
src/Config/Parser/MetadataParser/MetadataParser.php
src/Controller/ProfilerController.php
src/DependencyInjection/Compiler/ConfigParserPass.php
src/Resolver/InterfaceTypeResolver.php
src/Resources/config/aliases.yaml
src/Resources/config/services.yaml
tests/Config/Parser/MetadataParserTest.php
tests/Config/Parser/fixtures/annotations/Input/MateriaInput.php
tests/Config/Parser/fixtures/annotations/Type/Biped.php
tests/Config/Parser/fixtures/annotations/Type/Hero.php
tests/Config/Parser/fixtures/annotations/Type/Mandalorian.php
tests/Config/Parser/fixtures/annotations/Type/Sith.php
tests/Functional/App/GraphQL/Attributes/DemoInterface.php
tests/Functional/App/GraphQL/Attributes/QueryProvider.php
tests/Functional/App/GraphQL/Attributes/RootMutation.php
tests/Functional/App/GraphQL/Attributes/RootQuery.php
tests/Functional/App/GraphQL/Attributes/Type1.php
tests/Functional/App/GraphQL/Attributes/Type2.php
tests/Functional/App/config/attributes/config.yml
tests/Functional/InterfaceTypeResolver/InterfaceTypeResolverTest.php
tests/Transformer/ArgumentsTransformerTest.php
tests/Transformer/InputType4.php

| Bug fix?      | kind of
| Fixed tickets | #1171
- Handle default value on Input field and introduce a new attribute #[InputField]
- Update docs with example with attributes instead of annotation
- Rename `default` to `defaultValue` to be consistent in #[GQL\Arg] attribute (and deprecate the old one)

Cleanup Input default value and Fix #1171

---

docs/definitions/mutation.md

In the example, the resolve arguments are sent as an array instead of 2 seperate variables - this will create an error.

Fix mutation.md example

---

src/Transformer/ArgumentsTransformer.php
tests/Transformer/ArgumentsTransformerTest.php
tests/Transformer/Type1.php

| Fixed tickets | #1170
The `ArgumentsTransformer` should not validated arguments that are not `Input` or list of `Input`.  
For example, if we have a scalar returning an invalid object, we should not validate it on our side.  
In our case for example, we have scalars that turn `id` into doctrine entities so we can get entities in our methods. The scalar is in charge of validating that the object exists, but we shouldn't call the validation on the object returned by the scalar. Anyway, in a query or mutation, we should only validate inputted data through `InputObject`.

Validate only InputObject types fix #1170

---

src/Config/Parser/MetadataParser/MetadataParser.php
tests/Config/Parser/MetadataParserTest.php
tests/Config/Parser/fixtures/annotations/Invalid/InvalidArgumentNaming.php

This PR force an argument defined with `#[GQL\Arg]` or `@GQL\Arg` on a method to use a name matching one of the parameter of the method. 
It will avoid potential error following the last update and the arguments merging.

Ensure that a #[GQL\Arg] on method has a matching parameter

---

src/Config/Parser/MetadataParser/MetadataParser.php
tests/Config/Parser/MetadataParserTest.php
tests/Config/Parser/fixtures/annotations/Repository/PlanetRepository.php

| Fixed tickets | #1177
Ensure, the argument are declared in the same order as the related method.

Fix Arguments order of the method matter

---

src/Validator/InputValidator.php

| Fixed tickets | https://github.com/overblog/GraphQLBundle/issues/1180
We were overriding the `property` variable with the `property` from the `link`... this meant that the property (of an input or argument) had to match the property of the linked validation too.
This fixes that, allowing them to be separate, meaning you can have a property named `foo` and link it to a validation named `bar`.
Not sure if this is a breaking change... as technically the bug prevented people from having different properties -> entity properties, so there shouldn't be any skew anyway.

Allow for linked validations to be named differently to property

---

src/Config/Parser/MetadataParser/TypeGuesser/DocBlockTypeGuesser.php

Update DocBlockTypeGuesser.php - cs fix

---

src/Validator/InputValidator.php
tests/Functional/App/config/validator/mapping/Mutation.types.yml
tests/Functional/App/config/validator/mapping/Person.types.yml
tests/Functional/Validator/InputValidatorTest.php

| Fixed tickets | https://github.com/overblog/GraphQLBundle/issues/1182
This fixes the validation rules so that when passing a partial input object, only the fields passed are validated.

Don't validate fields that were not passed

---

.github/workflows/ci.yml
src/DependencyInjection/OverblogGraphQLExtension.php

| Fixed tickets | #1187 
With Symfony 7.1, `Symfony\Component\HttpKernel\DependencyInjection\Extension` is made for internal (Symfony) use only. This needs to be replaced with `Symfony\Component\DependencyInjection\Extension\Extension`.
No breaking changes with this deprecation update.

Support Symfony 7.1

---

src/Config/Parser/MetadataParser/MetadataParser.php
src/Transformer/ArgumentsTransformer.php
tests/Config/Parser/MetadataParserTest.php
tests/Config/Parser/fixtures/annotations/Repository/PlanetRepository.php
tests/Transformer/ArgumentsTransformerTest.php

| Fixed tickets | #1186 
This PR allows to inject the `ResolveInfo` into a query or mutation just by adding it to the list of auto-guessed arguments.  
Exemple:
````php
#[Query]
public function test(int $id, ResolveInfo $info) {
}
````
It only works with annotations/attributes and auto-guess parameters when the query resolver is auto-generated.

ResolveInfo injection in Query
