Resolver/ConfigResolver.php
Resolver/Resolver.php
Resources/config/services.yml
Tests/Resolver/ResolverTest.php
composer.json
phpunit.xml.dist

Should fix #2 but the true place of defaultResolverFn is in php lib [webonyx/graphql-php](https://github.com/webonyx/graphql-php).

Override defaultResolverFn to use PropertyAccess component

---

Relay/Mutation/MutationField.php
Relay/Node/GlobalIdField.php
Resolver/Resolver.php
Resolver/TypeResolver.php
Tests/Resolver/ArgResolverTest.php
Tests/Resolver/FieldResolverTest.php
Tests/Resolver/ResolverTest.php
Tests/Resolver/Toto.php

- Allow Mutation Payload to be an object (fix #3)
- Use PropertyAccess to retrieve id for GlobalIdField for default idFetcher resolver

Fix some accessor issues

---

Resources/views/GraphiQL/index.html.twig

Allow Graphiql to send cookies to cors-capable hosts

---

.travis.yml
Generator/TypeGenerator.php
README.md

* Fix type class loader
* Document Union and InputObject definition
* Travis required Symfony 3.1 for test

Type class loader bugfix and more

---

README.md
Relay/Connection/Paginator.php
Resources/doc/paginator.md
Tests/Relay/Connection/PaginatorTest.php

Paginator issue test and fix on forward method

---

Resources/doc/definitions/custom-scalar.md
Resources/doc/definitions/index.md

Add custom scalar documentation

---

Tests/Relay/Node/NodeFieldDefinitionTest.php

Fix NodeFieldDefinitionTest class name

---

composer.json

| Bug fix?      | yno
This will help to test latest version...

Add "0.7" composer version alias

---

Config/ObjectTypeDefinition.php
Config/TypeWithOutputFieldsDefinition.php
Generator/TypeGenerator.php
Tests/Functional/app/Resolver/NodeResolver.php
Tests/Functional/app/config/node/config.yml
Tests/Functional/app/config/node/mapping/Photo.types.yml

Fix resolve field bug

---

Request/BatchParser.php
Request/Parser.php

Fix request with empty variables json string

---

DependencyInjection/OverblogGraphQLExtension.php
ExpressionLanguage/ExpressionLanguage.php
Resources/config/services.yml

Remove expression language parser deprecation message for sf >= 3.2

---

Resources/views/GraphiQL/index.html.twig

Remove sf Toolbar updates when using GraphiQL

---

DependencyInjection/OverblogGraphQLExtension.php

Add builder classes as container resources

---

Tests/Functional/App/config/public/mapping/public.types.yml
Tests/Functional/Generator/TypeGeneratorTest.php

The missing tests for https://github.com/overblog/GraphQLBundle/pull/146

Added a test on fieldDefaultPublic

---

Error/ErrorHandler.php
Tests/Error/ErrorHandlerTest.php

Fix error handler to white list `GraphQL\Error\InvariantViolation`

---

DependencyInjection/Configuration.php
Tests/Functional/app/config/queryComplexity/config.yml

Allows env vars for security query sections

---

Generator/TypeGenerator.php
Tests/Functional/App/TestKernel.php
Tests/Functional/BootTest.php
Tests/Functional/Controller/GraphControllerTest.php
composer.json

| BC breaks?    | unsure
| Fixed tickets | #189 
I haven't seen all the comments in the ticket before making my code, I'll double check if I'm missing something now

Removed Symfony ClassLoader dependency

---

.travis.yml
Resolver/TypeResolver.php
Tests/Resolver/TypeResolverTest.php

- Sending scrutinizer only on one build

Improving scrutinizer handling on travis

---

Config/Parser/YamlParser.php
Config/TypeWithOutputFieldsDefinition.php
Definition/Argument.php
Definition/Builder/SchemaBuilder.php
DependencyInjection/Configuration.php
Error/UserErrors.php
EventListener/RequestFilesListener.php
Executor/Executor.php
GraphQL/Relay/Mutation/MutationFieldResolver.php
GraphQL/Relay/Node/PluralIdentifyingRootFieldResolver.php
Relay/Connection/Paginator.php
Request/Executor.php
Resolver/AbstractResolver.php
Resolver/Resolver.php
Resolver/TypeResolver.php
Tests/Definition/ArgumentTest.php
Tests/DependencyInjection/Compiler/ResolverTaggedServiceMappingPassTest.php
Tests/DependencyInjection/OverblogGraphQLTypesExtensionTest.php
Tests/ExpressionLanguage/AuthorizationExpressionProviderTest.php
Tests/ExpressionLanguage/ConfigExpressionProviderTest.php
Tests/Functional/App/Mutation/SimplePromiseMutation.php
Tests/Functional/Command/DebugCommandTest.php
Tests/Functional/Command/GraphDumpSchemaCommandTest.php
Tests/Functional/TestCase.php
Tests/Relay/Mutation/MutationFieldDefinitionTest.php
Tests/Relay/Node/NodeFieldDefinitionTest.php
Tests/Relay/Node/PluralIdentifyingRootFieldDefinitionTest.php

I change the comment style on properties as your have both short and long

Change the properties comment style

---

Resources/doc/definitions/schema.md
Resources/doc/index.md

Docs: Symfony Flex installation

---

DependencyInjection/OverblogGraphQLTypesExtension.php
Tests/Functional/App/config/access/config.yml

Protect against duplicate mapping file

---

Resources/doc/definitions/schema.md

Add the argument specification in the query example

Add the argument specification in the query expl

---

README.md

Add some community documentation

---

README.md

Just adding the whole documentation index to the readme so that we can easily find some info we need.

Add the whole documentation index to the readme

---

Config/Parser/XmlParser.php
Config/Parser/YamlParser.php
Tests/Functional/App/config/plural/mapping/empty.types.xml
Tests/Functional/Type/DefinitionTest.php

 Fix some weird behaviors when parsing empty config files

---

Resources/doc/definitions/resolver.md

Improve resolver documentation

---

Tests/Functional/App/Resolver/PluralResolver.php
Tests/Functional/App/config/node/config.yml
Tests/Functional/App/config/node/mapping/node_type.yml
Tests/Functional/App/config/plural/config.yml
Tests/Functional/App/config/plural/mapping/Query.types.xml

Modify tests to cover all resolvers declaration

---

Config/ObjectTypeDefinition.php
ExpressionLanguage/ExpressionFunction.php
Tests/DependencyInjection/Compiler/ResolverTaggedServiceMappingPassTest.php
Tests/Error/ErrorHandlerTest.php
Tests/Executor/Promise/Adapter/ReactPromiseAdapterTest.php
Tests/ExpressionLanguage/ExpressionFunctionTest.php
Tests/Functional/App/config/config.yml

- Just some overall small code improvements of things which I'm finding while digging in the code

Overall code and tests improvements

---

Config/TypeWithOutputFieldsDefinition.php
DependencyInjection/Compiler/AutoMappingPass.php
DependencyInjection/Compiler/AutowiringTypesPass.php
DependencyInjection/Compiler/TaggedServiceMappingPass.php
DependencyInjection/Configuration.php
DependencyInjection/TypesConfiguration.php
Relay/Connection/Paginator.php
Request/Executor.php
Resolver/TypeResolver.php
Tests/DIContainerMockTrait.php
Tests/ExpressionLanguage/ExpressionFunctionTest.php
Tests/Functional/Relay/Connection/ConnectionTest.php
Tests/Resolver/AbstractProxyResolverTest.php

@mcg-web requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/overblog/GraphQLBundle/

Scrutinizer Auto-Fixes

---

Relay/Connection/Paginator.php

Correct error on paginator promise

---

Command/GraphQLDumpSchemaCommand.php

Fix available formats when using the dump command

---

README.md

- Just links to talks and slides to help people start

Adding talks slides and videos

---

README.md
Resources/doc/definitions/resolver.md
Resources/doc/definitions/solving-n-plus-1-problem.md
Resources/doc/index.md

- added "Solving N+1 problem" section
- added dev version and downloads badges
- Improved requirements section

Improve documentation

---

Config/Processor.php
Config/Processor/BuilderProcessor.php
Config/Processor/ExpressionProcessor.php
Config/Processor/InheritanceProcessor.php
Config/Processor/NamedConfigProcessor.php
Config/Processor/ProcessorInterface.php
Config/Processor/RelayProcessor.php
Config/TypeWithOutputFieldsDefinition.php
DependencyInjection/Configuration.php
DependencyInjection/OverblogGraphQLExtension.php
DependencyInjection/OverblogGraphQLTypesExtension.php
DependencyInjection/TypesConfiguration.php
Generator/TypeGenerator.php
README.md
Resources/doc/definitions/index.md
Resources/doc/definitions/type-inheritance.md
Tests/Config/Processor/BuilderProcessorTest.php
Tests/Config/Processor/InheritanceProcessorTest.php
Tests/DependencyInjection/OverblogGraphQLTypesExtensionTest.php
Tests/Functional/App/config/inheritance/config.yml
Tests/Functional/App/config/inheritance/mapping/Decorators.types.yaml
Tests/Functional/App/config/inheritance/mapping/Enum.types.yaml
Tests/Functional/App/config/inheritance/mapping/Query.types.yaml
Tests/Functional/App/config/inheritance/mapping/QueryHelloWord.types.yaml
Tests/Functional/Inheritance/InheritanceTest.php

Introduce inheritance

---

Definition/ConfigProcessor/AclConfigProcessor.php
Definition/ConfigProcessor/WrapArgumentConfigProcessor.php
Definition/Type/SchemaDecorator.php
Resolver/Resolver.php
Resources/config/definition_config_processors.yml
Tests/Functional/App/config/argumentWrapper/config.yml
Tests/Functional/App/config/argumentWrapper/mapping/query.types.yml
Tests/Functional/ArgumentWrapper/ArgumentWrapperTest.php

| BC breaks?    |  no
| Fixed tickets | slack @Kocal @tristanbes 

Fix resolver args wrapper BC

---

Relay/Connection/ConnectionDefinition.php

allows to define custom resolver for cursor

fixed ConnectionDefinition config

---

Resources/doc/error-handling/index.md

Fix documentation about custom exception mapping to reflect [this change](https://github.com/overblog/GraphQLBundle/blob/cab67b3ccb23f57f914e66f8520de5e0d272c06d/UPGRADE-0.11.md#errors-handler).

Update custom exception mapping doc

---

Resources/doc/definitions/type-system/input-object.md

Fix bug documentation input-object

Change graphql format

---

README.md
Resources/doc/security/fields-access-control.md
Resources/doc/security/index.md
Resources/doc/security/object-access-control.md

Documentation about object access control using a decorator type

Object access control

---

Resources/doc/definitions/graphql-schema-language.md

| Fixed tickets | #328
Rewrite some parts of [GraphQL Schema Language](https://github.com/overblog/GraphQLBundle/blob/master/Resources/doc/definitions/graphql-schema-language.md) documentation, with more concrete examples.
Also add section for mutations.
The changes are visible [here](https://github.com/Kocal/GraphQLBundle/blob/doc/improve-graphql-schema-language-documentation/Resources/doc/definitions/graphql-schema-language.md).

doc(graphql-schema-language): rewrite and add section for mutations

---

Tests/Functional/App/config/multipleQueries/config.yml
Tests/Functional/App/config/multipleQueries/mapping/RootQuery.types.yml
Tests/Functional/MultipleQueries/MultipleQueriesTest.php

Add multiple queries tests

---

Resolver/Resolver.php
Tests/Functional/App/config/argumentWrapper/config.yml
Tests/Functional/App/config/argumentWrapper/mapping/query.types.yml
Tests/Functional/ArgumentWrapper/ArgumentWrapperTest.php

Fix argument wrapper with access

---

.gitattributes
.gitignore
.travis.yml
CONTRIBUTING.md
benchmarks/Benchmark.php
benchmarks/Config/ParserGraphQLParserBench.php
benchmarks/Mock/ContainerBuilder.php
benchmarks/Request/ParserBench.php
benchmarks/fixtures/schema.graphql
composer.json
phpbench.json

Add some code quality tools

---

src/Definition/Builder/TypeFactory.php
src/DependencyInjection/Compiler/ConfigTypesPass.php
src/Resources/config/services.yml

Fix (#385) generated type class loader

---

.travis.yml
Resolver/AccessResolver.php
Tests/Functional/App/config/access/mapping/access.types.yml
Tests/Functional/Security/AccessTest.php

Fix acl with array

---

docs/definitions/graphql-schema-language.md
src/Config/Parser/GraphQL/ASTConverter/CustomScalarNode.php
src/Config/Parser/GraphQL/ASTConverter/DescriptionNode.php
src/Config/Parser/GraphQL/ASTConverter/DirectiveNode.php
src/Config/Parser/GraphQL/ASTConverter/EnumNode.php
src/Config/Parser/GraphQL/ASTConverter/FieldsNode.php
src/Config/Parser/GraphQL/ASTConverter/InputObjectNode.php
src/Config/Parser/GraphQL/ASTConverter/InterfaceNode.php
src/Config/Parser/GraphQL/ASTConverter/NodeInterface.php
src/Config/Parser/GraphQL/ASTConverter/ObjectNode.php
src/Config/Parser/GraphQL/ASTConverter/TypeNode.php
src/Config/Parser/GraphQL/ASTConverter/UnionNode.php
src/Config/Parser/GraphQLParser.php
tests/Config/Parser/GraphQLParserTest.php
tests/Config/Parser/fixtures/graphql/schema-0.11.graphql
tests/Config/Parser/fixtures/graphql/schema.graphql
tests/Config/Parser/fixtures/graphql/schema.php

Support deprecation directive

---

src/Config/Processor.php
src/Config/Processor/NamedConfigProcessor.php
src/Definition/Builder/SchemaBuilder.php
src/Definition/Type/ExtensibleSchema.php
src/DependencyInjection/TypesConfiguration.php
src/Generator/TypeGenerator.php
tests/DependencyInjection/OverblogGraphQLTypesExtensionTest.php
tests/Functional/App/config/multipleSchema/config.yml
tests/Functional/App/config/multipleSchema/mapping/internal/InternalQuery.yaml
tests/Functional/App/config/multipleSchema/mapping/public/PublicQuery.yaml
tests/Functional/Inheritance/InheritanceTest.php
tests/Functional/MultipleSchema/MultipleSchemaTest.php
tests/Functional/TestCase.php

Fix multiple schema with same duplicated type names

---

src/Config/Parser/GraphQL/ASTConverter/FieldsNode.php
tests/Config/Parser/fixtures/graphql/schema.php

Fix parsing of default value

---

src/Definition/Type/ExtensibleSchema.php
tests/Functional/App/config/multipleSchema/config.yml
tests/Functional/MultipleSchema/MultipleSchemaTest.php

Fix infinity loop when resolving unknown type

---

src/Definition/ConfigProcessor/AclConfigProcessor.php
src/Generator/TypeGenerator.php
src/Resolver/AccessResolver.php
src/Resources/skeleton/OutputFieldConfig.php.skeleton
tests/Functional/App/config/access/mapping/access.types.yml
tests/Functional/Security/AccessTest.php

Execute resolverCallback for access only if needed

---

src/DependencyInjection/Compiler/GlobalVariablesPass.php

| Fixed tickets | #418 
This fixes #418

Fix variable name, fixes #418

---

.travis.yml

Prepare for Symfony 4.2

---

src/Relay/Mutation/InputDefinition.php
src/Relay/Mutation/PayloadDefinition.php
tests/Functional/App/config/multipleSchema/config.yml
tests/Functional/App/config/multipleSchema/mapping/internal/InternalAddUserPayload.yaml
tests/Functional/App/config/multipleSchema/mapping/internal/InternalMutation.yaml
tests/Functional/App/config/multipleSchema/mapping/public/PublicAddUserInput.yaml
tests/Functional/App/config/multipleSchema/mapping/public/PublicAddUserPayload.yaml
tests/Functional/App/config/multipleSchema/mapping/public/PublicMutation.yaml
tests/Functional/MultipleSchema/MultipleSchemaTest.php

Fix using custom names on a relay-mutation Input and Payload

---

.travis.yml
src/Config/CustomScalarTypeDefinition.php
src/Config/EnumTypeDefinition.php
src/Config/InputObjectTypeDefinition.php
src/Config/InterfaceTypeDefinition.php
src/Config/ObjectTypeDefinition.php
src/Config/TypeDefinition.php
src/Config/TypeWithOutputFieldsDefinition.php
src/Config/UnionTypeDefinition.php
src/DependencyInjection/Configuration.php
src/DependencyInjection/TypesConfiguration.php
tests/Functional/Inheritance/InheritanceTest.php

Remove deprecation messages for symfony 4.2

---

.travis.yml

Add travis php 7.3 build

---

src/Resolver/AccessResolver.php
tests/Functional/App/Resolver/ConnectionResolver.php
tests/Functional/App/config/access/mapping/access.types.yml
tests/Functional/App/config/connection/services.yml
tests/Functional/Security/AccessTest.php

Allow promise for AccessResolver::checkAccessForStrictMode

---

src/ExpressionLanguage/ExpressionLanguage.php
src/Generator/TypeGenerator.php
tests/Functional/App/Resolver/NodeResolver.php
tests/Functional/App/Service/PrivateService.php
tests/Functional/App/config/access/config.yml
tests/Functional/App/config/access/mapping/access.types.yml
tests/Functional/App/config/node/config.yml
tests/Functional/App/config/node/mapping/node_type.yml

Fix global variables in access

---

UPGRADE-0.12.md
docs/helpers/relay-paginator.md
src/Relay/Connection/ConnectionBuilder.php
src/Relay/Connection/ConnectionInterface.php
src/Relay/Connection/EdgeInterface.php
src/Relay/Connection/Output/Connection.php
src/Relay/Connection/Output/ConnectionBuilder.php
src/Relay/Connection/Output/DeprecatedPropertyPublicAccessTrait.php
src/Relay/Connection/Output/Edge.php
src/Relay/Connection/Output/PageInfo.php
src/Relay/Connection/PageInfoInterface.php
src/Relay/Connection/Paginator.php
src/Resolver/AccessResolver.php
tests/Functional/App/Resolver/ConnectionResolver.php
tests/Relay/Connection/AbstractConnectionBuilderTest.php
tests/Relay/Connection/ConnectionBuilderFromPromisedTest.php
tests/Relay/Connection/ConnectionBuilderTest.php
tests/Relay/Connection/Output/ConnectionBuilderFromPromisedTest.php
tests/Relay/Connection/Output/ConnectionBuilderTest.php
tests/Relay/Connection/Output/DeprecatedPropertyPublicAccessTraitTest.php
tests/Relay/Connection/PaginatorTest.php
tests/Relay/Connection/fixtures/CustomConnection.php
tests/Relay/Connection/fixtures/CustomEdge.php

see #412 
Add a way to customize the way the Connection & Edges are built when using the Paginator.

Relay pagination customization

---

docs/index.md
src/Resources/config/routing/graphql.yml
src/Resources/config/routing/multiple.yaml
src/Resources/config/routing/single.yaml

Make routes prefixes configurable

---

docs/annotations/annotations-reference.md
src/Annotation/Access.php
src/Annotation/Deprecated.php
src/Annotation/Description.php
src/Annotation/FieldsBuilder.php
src/Annotation/IsPublic.php
src/Annotation/Query.php
src/Annotation/Type.php
src/Config/Parser/AnnotationParser.php
tests/Config/Parser/AnnotationParserTest.php
tests/Config/Parser/fixtures/annotations/Type/Crystal.php

Add the @FieldsBuilder annotation to handle the new Fields builder feature (see #438)

Add missing @FieldsBuilder annotation

---

composer.json
src/DependencyInjection/Configuration.php
src/DependencyInjection/OverblogGraphQLExtension.php
src/Generator/TypeGenerator.php
src/Resources/config/services.yml
tests/Generator/TypeGenerator.php
tests/Generator/TypeGeneratorTest.php

Fix type cache dir permission with symfony default cache dir

---

docs/definitions/resolver.md

Add missing closing bracket

---

composer.json
lib/generator/composer.json
tests/Config/Parser/GraphQLParserTest.php
tests/Error/ErrorHandlerTest.php
tests/Functional/Command/GraphDumpSchemaCommandTest.php
tests/Functional/Exception/ExceptionTest.php
tests/Functional/MultipleQueries/MultipleQueriesTest.php
tests/Functional/TestCase.php
tests/Resolver/ResolverTest.php
tests/VersionHelper.php

Support webonyx/graphql-php 0.13

---

src/Resolver/ResolverMap.php

Fix map return type

---

docs/definitions/builders/field.md
docs/definitions/builders/fields.md

Doc field(s) builder adding new types

---

docs/definitions/type-inheritance.md

Clarify inheritance docs

---

src/Config/Parser/AnnotationParser.php
src/DependencyInjection/OverblogGraphQLTypesExtension.php
tests/Config/Parser/AnnotationParserTest.php

Fix annotation parser with multiple kernel

---

src/Config/Parser/AnnotationParser.php

Added default value for arguments

---

.travis.yml
phpunit.xml.dist
src/Command/GraphQLDumpSchemaCommand.php
src/Error/ErrorHandler.php
src/Event/EventDispatcherVersionHelper.php
src/Request/Executor.php
tests/DependencyInjection/Compiler/ResolverTaggedServiceMappingPassTest.php
tests/DependencyInjection/OverblogGraphQLTypesExtensionTest.php
tests/Functional/Controller/GraphControllerTest.php
tests/Functional/Relay/Node/GlobalTest.php
tests/Functional/Relay/Node/NodeTest.php
tests/Functional/Security/AccessTest.php
tests/Functional/TestCase.php
tests/Request/ExecutorTest.php

Remove Symfony 4.3 deprecations messages

---

UPGRADE-0.12.md
src/Executor/Executor.php
src/Executor/ExecutorInterface.php
src/Request/Executor.php
src/Resources/config/services.yml
tests/Executor/ExecutorTest.php
tests/Request/ExecutorTest.php

Refactor executor/ request executor

---

.travis.yml
README.md
composer.json
docs/definitions/coroutine-executor.md
docs/definitions/index.md
phpunit.xml.dist
src/DependencyInjection/Configuration.php
src/DependencyInjection/OverblogGraphQLExtension.php
src/Request/Executor.php
src/Resources/config/services.yaml
tests/Functional/App/config/config.yml

releated to webonyx/graphql-php/pull/486

Allow using GraphQL experimental Coroutine executor

---

docs/annotations/annotations-reference.md
src/Config/Parser/AnnotationParser.php
tests/Config/Parser/AnnotationParserTest.php
tests/Config/Parser/fixtures/annotations/Repository/PlanetRepository.php

Handle @IsPublic & @Access on @Provider to define default values

---

src/OverblogGraphQLBundle.php

Fix types register when using lazy command

---

.appveyor.yml
README.md
tests/Config/Parser/GraphQLParserTest.php
tests/DependencyInjection/OverblogGraphQLTypesExtensionTest.php
tests/Functional/Command/CompileCommandTest.php
tests/Functional/Command/DebugCommandTest.php
tests/Functional/Security/AccessTest.php
tests/VersionHelper.php

Add appveyor

---

src/CacheWarmer/CompileCacheWarmer.php
src/DependencyInjection/Configuration.php
src/DependencyInjection/OverblogGraphQLExtension.php

Allow env for "definitions.auto_compile" config

---

docs/definitions/resolver.md
docs/definitions/type-system/index.md
src/DependencyInjection/OverblogGraphQLExtension.php
src/Resources/config/graphql_resolvers.yaml

| Fixed tickets | #439 
For classes `Type`, `ResolverInterface` and `MutationInterface`

Register autoconfiguration for bundle classes

---

docs/annotations/index.md

add Mapping configuration sections to annotation docs

---

docs/annotations/annotations-reference.md

Related to #526. Does not fix it, but resolves some confusion.

fix and improve annotation doc for `@Provider`, `@Mutation` and `@Query`

---

docs/definitions/expression-language.md

Rework the Expression Language documentation:
* Add the **Contents** section with navigation references
* Replace the table of functions with a more readable list, which can be extended later
* Fix and add more examples to each function
* Correct some grammar mistakes
* Add new section **Backslashes in expressions**
* Add links to external resources
* Rework titles
* Rework some texts

Rework expression-language.md

---

src/Definition/Builder/SchemaBuilder.php
src/DependencyInjection/OverblogGraphQLExtension.php
src/Request/Executor.php
tests/Functional/App/Resolver/NullResolverMap.php
tests/Functional/App/Resolver/SchemaLanguageQueryResolverMap.php
tests/Functional/App/config/schemaLanguage/config.yml

Add a test covering callable resolverMap

---

src/Config/Processor/InheritanceProcessor.php
src/Config/Processor/RelayProcessor.php
tests/Functional/App/config/inheritance/mapping/Relay.types.yaml
tests/Functional/Inheritance/InheritanceTest.php

We are using this fix internally, time to get this merged :-)

Add inheritance support to relay processor

---

src/DependencyInjection/Compiler/ResolverMethodAliasesPass.php
src/OverblogGraphQLBundle.php
tests/Functional/App/GraphQL/HelloWord/Type/QueryType.php
tests/Functional/App/IsolatedResolver/EchoResolver.php
tests/Functional/App/config/autoConfigure/config.yml
tests/Functional/AutoConfigure/HelloWordTest.php

Fix resolver aliases when using autoconfig

---

UPGRADE-0.13.md
composer.json
docs/definitions/resolver.md
src/DependencyInjection/Configuration.php
src/DependencyInjection/OverblogGraphQLExtension.php
src/GraphQL/Relay/Mutation/MutationFieldResolver.php
src/GraphQL/Relay/Node/GlobalIdFieldResolver.php
src/Resolver/FieldResolver.php
src/Resolver/Resolver.php
src/Resources/config/definition_config_processors.yaml
src/Resources/config/services.yaml
tests/Functional/App/Mutation/SimplePromiseMutation.php
tests/Resolver/ResolverFieldTest.php

Improve default field resolver performance

---

src/Config/Processor/InheritanceProcessor.php
tests/Functional/App/config/inheritance/mapping/Decorators.types.yaml
tests/Functional/Inheritance/InheritanceTest.php

| BC breaks?    | maybe
| Fixed tickets | #565

Fix interface merge

---

docs/definitions/type-system/interface.md

Update the documentation (Chapter "Interface")

Documentation

---

composer.json

Move phpstan setup in compose.json file

move phpstan in composer.json file

---

composer.json
phpstan-baseline.neon

Remove some error reported from PHPStan by using `phpstan/phpstan-symfony` extension

remove some error reported from phpstan

---

composer.json

Use specific version of phpcs

---

.travis.yml
composer.json
src/Command/CompileCommand.php
src/Command/DebugCommand.php
src/Command/GraphQLDumpSchemaCommand.php
src/Resources/config/services.yml
tests/Config/Parser/GraphQLParserTest.php
tests/Functional/App/TestKernel.php
tests/Functional/Controller/GraphControllerTest.php
tests/Functional/ForwardCompatTestCaseTrait.php
tests/Functional/TestCase.php
tests/Functional/Upload/UploadTest.php

Add support for Symfony 5

---

.travis.yml
composer.json
phpstan-baseline.neon
src/Validator/Constraints/ExpressionValidator.php
tests/Functional/App/config/validator/mapping/Mutation.types.yml
tests/Functional/TestCase.php
tests/Functional/Validator/ExpectedErrors.php
tests/Functional/Validator/InputValidatorTest.php

Fix travis build for Symfony 5

---

src/Resources/config/commands.yaml
tests/Functional/App/TestKernel.php
tests/Functional/App/config/access/config.yml
tests/Functional/App/config/argumentWrapper/config.yml
tests/Functional/App/config/config.yml
tests/Functional/App/config/connection/config.yml
tests/Functional/App/config/customScalar/config.yml
tests/Functional/App/config/definition/config.yml
tests/Functional/App/config/disableIntrospection/config.yml
tests/Functional/App/config/exception/config.yml
tests/Functional/App/config/global/config.yml
tests/Functional/App/config/inheritance/config.yml
tests/Functional/App/config/multipleQueries/config.yml
tests/Functional/App/config/multipleSchema/config.yml
tests/Functional/App/config/mutation/config.yml
tests/Functional/App/config/node/config.yml
tests/Functional/App/config/plural/config.yml
tests/Functional/App/config/public/config.yml
tests/Functional/App/config/queryComplexity/config.yml
tests/Functional/App/config/queryComplexityEnv/config.yml
tests/Functional/App/config/queryMaxDepth/config.yml
tests/Functional/App/config/queryMaxDepthEnv/config.yml
tests/Functional/App/config/schemaLanguage/config.yml
tests/Functional/App/config/upload/config.yml
tests/Functional/App/config/validation/config.yml

Remove obsolete kernel.root_dir param

---

src/Config/Parser/AnnotationParser.php

remove php7.4 deprecation messages

---

phpstan-baseline.neon
src/ExpressionLanguage/ExpressionFunction/Security/GetUser.php
src/ExpressionLanguage/ExpressionFunction/Security/HasAnyPermission.php
src/ExpressionLanguage/ExpressionFunction/Security/HasAnyRole.php
src/ExpressionLanguage/ExpressionFunction/Security/HasPermission.php
src/ExpressionLanguage/ExpressionFunction/Security/HasRole.php
src/ExpressionLanguage/ExpressionFunction/Security/Helper.php
src/ExpressionLanguage/ExpressionFunction/Security/IsAnonymous.php
src/ExpressionLanguage/ExpressionFunction/Security/IsAuthenticated.php
src/ExpressionLanguage/ExpressionFunction/Security/IsFullyAuthenticated.php
src/ExpressionLanguage/ExpressionFunction/Security/IsGranted.php
src/ExpressionLanguage/ExpressionFunction/Security/IsRememberMe.php
src/Resources/config/services.yaml
src/Security/Security.php
tests/DIContainerMockTrait.php
tests/ExpressionLanguage/ExpressionFunction/Security/GetUserTest.php
tests/ExpressionLanguage/ExpressionFunction/Security/HasAnyPermissionTest.php
tests/ExpressionLanguage/ExpressionFunction/Security/HasAnyRoleTest.php
tests/ExpressionLanguage/ExpressionFunction/Security/HasPermissionTest.php
tests/ExpressionLanguage/ExpressionFunction/Security/HasRoleTest.php
tests/ExpressionLanguage/ExpressionFunction/Security/IsAnonymousTest.php
tests/ExpressionLanguage/ExpressionFunction/Security/IsAuthenticatedTest.php
tests/ExpressionLanguage/ExpressionFunction/Security/IsFullyAuthenticatedTest.php
tests/ExpressionLanguage/ExpressionFunction/Security/IsGrantedTest.php
tests/ExpressionLanguage/ExpressionFunction/Security/IsRememberMeTest.php
tests/ExpressionLanguage/TestCase.php
tests/Security/SecurityTest.php

Make security core component optional

---

composer.json

| BC breaks?    |no
| Documented?   |no
| Fixed tickets | #637

Require symfony/property-access

---

src/Resolver/TypeResolver.php

Changed the error message to use better english sentence. I'm not sure what the target branch for this should be.

Change error message

---

docs/helpers/relay-paginator.md

fix typo in relay paginator helper documentation

---

src/Validator/ValidationNode.php

Same fix as #686 but preserving older PHP versions

Fix ValidationNode.php

---

.travis.yml
composer.json
tests/Resolver/ResolverTest.php

Increase php memory for composer with php 5.6

---

README.md

Update the top badges to show information about the appropriate version

Update badges (0.11)

---

README.md

Update top badges to show information about the appropriate version

Update badges (0.12)

---

README.md

Update top badges to show information about the appropriate version

Update badges (0.13)

---

src/Resolver/FieldResolver.php
tests/Resolver/ResolverFieldTest.php
tests/Resolver/Toto.php

Fix resolver field with same property/method name

---

src/Config/Parser/AnnotationParser.php

Fix the attribute name for AnnotationParser fieldBuilder error message

---

src/Annotation/Access.php
src/Annotation/Arg.php
src/Annotation/Deprecated.php
src/Annotation/Description.php
src/Annotation/Field.php
src/Annotation/FieldsBuilder.php
src/Annotation/IsPublic.php
src/Annotation/Relay/Edge.php
src/Annotation/TypeInterface.php
src/Annotation/Union.php
src/Config/Parser/AnnotationParser.php
tests/Config/Parser/fixtures/annotations/Invalid/InvalidAccess.php

Fix annotations

---

src/Config/Parser/AnnotationParser.php

Due to the type hint (master only), ensure the value isset before accessing it

Fix parser on enum

---

phpunit.xml.dist

Noticed that phpunit warns about old config schema.

Update phpunit config-schema

---

README.md
src/DependencyInjection/Compiler/TypeGeneratorPass.php

Update links in README.md

---

src/Validator/InputValidator.php

Fix bug in validator

---

.appveyor.yml

Fix appveyor ci build

---

.github/workflows/ci.yml

Fix coveralls variables envs

---

src/Transformer/ArgumentsTransformer.php
tests/Transformer/ArgumentsTransformerTest.php

[PATCH] Fix error for non-nullable array of non-nullable elements annotation

---

src/Annotation/Scalar.php

Allow `#GQL\Scalar` to be repeatable.

Fix repeatable scalar attribute

---

.gitignore
composer.json

Lock phpbench to v1 alpha 7

---

src/DependencyInjection/Compiler/TaggedServiceMappingPass.php
src/Resolver/AbstractResolver.php
src/Resolver/FluentResolverInterface.php
tests/DependencyInjection/Compiler/ResolverTaggedServiceMappingPassTest.php
tests/Resolver/AbstractProxyResolverTest.php
tests/Resolver/TypeResolverTest.php

allow resolver solution to be private service
| BC breaks?    | yes/no

Keep original accessibility option for services tagged as resolver

---

src/Generator/TypeBuilder.php

Fix default value

---

src/Config/Parser/GraphQLParser.php

This fixes the one and only PHPStan error on 0.14.
See #908

Fix PHPStan error

---

tests/Functional/App/config/config.yml

This fixes 15 failing tests.
See #908

Enable validator in tests

---

.github/workflows/ci.yml

Drop `COMPOSER_ROOT_VERSION`

---

src/DependencyInjection/Compiler/AliasedPass.php
src/DependencyInjection/Compiler/GraphQLServicesPass.php
src/Resources/config/expression_language_functions.yaml
tests/DependencyInjection/Compiler/GraphQLServicesPassTest.php
tests/Functional/App/config/validator/config.yml

Forgot to remove these: https://github.com/overblog/GraphQLBundle/pull/893
This means that there is not a good test coverage on this part.

Remove more deprecations

---

.github/workflows/ci.yml
src/DataCollector/GraphQLCollector.php
tests/Controller/ProfilerControllerTest.php
tests/Functional/App/TestKernel.php

Test symfony 5.4

---

UPGRADE.md
src/Annotation/TypeInterface.php

Tweaked it a bit and made the UPGRADE doc more clear.

Tweak TypeInterface

---

.github/workflows/ci.yml
composer.json
src/Definition/Argument.php

Needs a rebase when this is merged:
- https://github.com/overblog/GraphQLBundle/pull/941
- https://github.com/overblog/GraphQLBundle/pull/942

Test on PHP 8.1

---

.appveyor.yml
.github/workflows/ci.yml
composer.json

`master` branch will be PHP 8.0+

Drop PHP 7.4 support

---

composer.json
phpstan-baseline.neon
src/EventListener/TypeDecoratorListener.php
src/Validator/InputValidator.php
src/Validator/ValidationNode.php
tests/EventListener/TypeDecoratorListenerTest.php

I had to change some things in the second commit to get it working.
Tests seem to pass, so let's give it a shot? :) 
See:
- https://github.com/webonyx/graphql-php/commit/44ed079229b6e954ba4edd55e65d697a2df67211

Sync with upstream `webonyx/graphql-php` changes

---

composer.json

Allow all `psr/log`

---

UPGRADE.md
src/EventListener/RequestListener.php
src/Resources/config/listeners.yaml

use `request` object from Context instead

Remove `request_files` from context

---

.gitignore
.php-cs-fixer.dist.php
composer.json
src/Config/Parser/MetadataParser/TypeGuesser/DoctrineTypeGuesser.php
src/Definition/Type/CustomScalarType.php
src/EventListener/TypeDecoratorListener.php
src/ExpressionLanguage/ExpressionLanguage.php
src/Generator/TypeBuilder.php
src/Relay/Mutation/MutationFieldDefinition.php
src/Relay/Node/GlobalIdFieldDefinition.php
src/Relay/Node/NodeFieldDefinition.php
src/Relay/Node/PluralIdentifyingRootFieldDefinition.php
src/Validator/ValidationNode.php
tests/Config/Parser/MetadataParserTest.php
tests/DependencyInjection/Compiler/ConfigParserPassTest.php
tests/EventListener/TypeDecoratorListenerTest.php
tests/Executor/ExecutorTest.php
tests/Executor/Promise/Adapter/ReactPromiseAdapterTest.php
tests/Functional/TestCase.php
tests/Relay/Connection/ConnectionBuilderFromPromisedTest.php
tests/Relay/Connection/ConnectionBuilderTest.php
tests/Transformer/ArgumentsTransformerTest.php

Upgrade php cs fixer

---

src/Definition/Type/ExtensibleSchema.php
src/Resolver/TypeResolver.php
tests/Functional/MultipleSchema/MultipleSchemaTest.php

Fixes #886
| Bug fix?      |no
| Documented?   |no
| Fixed tickets | #886

Remove `addDefaultFallBackToTypeLoader`

---

.github/workflows/ci.yml

This version should solve the flaky installs / caches.

Use ramsey/composer-install v2

---

.github/workflows/ci.yml

Cron CI execution

---

UPGRADE.md
src/Annotation/FieldsBuilder.php
src/DependencyInjection/Compiler/TaggedServiceMappingPass.php
tests/Functional/App/IsolatedResolver/EchoQuery.php

Remove 1.0 obsolete features

---

composer.json
tests/Config/Parser/MetadataParser/TypeGuesser/DocBlockTypeGuesserTest.php
tests/Functional/Command/fixtures/schema.descriptions.json
tests/Functional/Command/fixtures/schema.graphql
tests/Functional/Command/fixtures/schema.json
tests/Functional/Command/fixtures/schema.modern.json

Fix tests & update php-documentor to ^1.6.1

---

README.md

| Fixed tickets | -
As I described in the title, I just corrected a link in README.md

Correct broken link in README.md

---

.github/workflows/ci.yml
docs/definitions/type-system/enum.md
src/Config/EnumTypeDefinition.php
src/Config/Parser/MetadataParser/MetadataParser.php
src/Definition/Type/PhpEnumType.php
src/Generator/TypeBuilder.php
src/Transformer/ArgumentsTransformer.php
tests/Config/Parser/MetadataParserTest.php
tests/Config/Parser/fixtures/annotations/Enum/Color.php
tests/Definition/Type/PhpEnumTypeTest.php
tests/Functional/App/config/enumPhp/config.yml
tests/Functional/App/config/enumPhp/mapping/EnumPhp.types.yml
tests/Functional/EnumPhp/EnumPhp.php
tests/Functional/EnumPhp/EnumPhpBacked.php
tests/Functional/EnumPhp/EnumPhpTest.php
tests/Functional/TestCase.php
tests/Transformer/ArgumentsTransformerTest.php
tests/Transformer/EnumPhp.php

| Fixed tickets | #990 
Add PHP 8.1 enums support.

PHP 8.1 Enum support

---

src/Definition/Type/PhpEnumType.php
src/Transformer/ArgumentsTransformer.php
tests/Transformer/ArgumentsTransformerTest.php

Fix PHP enum transformation by Argument Transformer

Fix enum arguments transformer & tests

---

src/Controller/ProfilerController.php
src/Validator/ValidationNode.php

| Documented?   |no
Fix Deprecation warnings for PHP 8.2

Fix deprecation warning for PHP 8.2

---

.github/workflows/ci.yml

`ramsey/composer-install` includes caching.

Remove redundant caching from CI

---

docs/attributes/attributes-reference.md

Fix a tiny typo in the attributes documentation.

Fix typo in attributes documentation
